const en = {
  "checking": "Checking your Shopify connection and trial…",
  "trialActive": "Your 14-day Pro + AI trial is active",
  "workspaceReady": "Your WhachatCRM workspace is ready",
  "choosePlan": "Choose a plan to continue",
  "reconnect": "Reopen WhachatCRM from Shopify",
  "eligibility": "We need to check your trial eligibility",
  "notActive": "We couldn’t activate your trial yet",
  "connectDescription": "Connect WhatsApp or another messaging channel to bring customer conversations into Inbox. You can keep using WhatsApp Business App with WhatsApp Coexistence.",
  "trialDescription": "No paid plan selection is needed to use your active trial. Your original trial end date stays the same.",
  "connect": "Connect a channel",
  "inbox": "Enter Inbox",
  "plansAnytime": "View plans anytime",
  "noAccess": "This store has no active trial or paid access. Installing again does not restart a trial.",
  "plans": "View Shopify plans",
  "reopenDescription": "Open the app from your Shopify admin to reconnect. If you returned from installation, allow cookies for this app and try opening it again.",
  "admin": "Open Shopify admin",
  "checkAgain": "Check connection again",
  "supportDescription": "Your store’s trial history needs review. We have not started or reset a trial.",
  "support": "Contact support",
  "retryDescription": "Your trial is not confirmed. Try again; retrying will not restart or extend a previously used trial.",
  "busy": "Checking…",
  "retry": "Try again",
  "verificationError": "We couldn’t verify your connection. Please try again or reopen the app from Shopify."
};
type Copy = Record<keyof typeof en, string>;
const es: Copy = {
  "checking": "Comprobando tu conexión de Shopify y tu prueba…",
  "trialActive": "Tu prueba de 14 días de Pro + IA está activa",
  "workspaceReady": "Tu espacio de trabajo de WhachatCRM está listo",
  "choosePlan": "Elige un plan para continuar",
  "reconnect": "Vuelve a abrir WhachatCRM desde Shopify",
  "eligibility": "Necesitamos revisar si tu tienda puede recibir una prueba",
  "notActive": "Aún no hemos podido activar tu prueba",
  "connectDescription": "Conecta WhatsApp u otro canal de mensajería para llevar las conversaciones de tus clientes a Inbox. Puedes seguir usando WhatsApp Business App con WhatsApp Coexistence.",
  "trialDescription": "No necesitas elegir un plan de pago para usar tu prueba activa. La fecha original de finalización de tu prueba no cambia.",
  "connect": "Conectar un canal",
  "inbox": "Entrar a Inbox",
  "plansAnytime": "Ver planes cuando quieras",
  "noAccess": "Esta tienda no tiene una prueba activa ni acceso de pago. Volver a instalar no reinicia una prueba.",
  "plans": "Ver planes de Shopify",
  "reopenDescription": "Abre la app desde tu panel de Shopify para volver a conectarla. Si acabas de instalarla, permite las cookies de esta app y vuelve a abrirla.",
  "admin": "Abrir el panel de Shopify",
  "checkAgain": "Comprobar la conexión otra vez",
  "supportDescription": "Necesitamos revisar el historial de prueba de tu tienda. No hemos iniciado ni reiniciado una prueba.",
  "support": "Contactar con soporte",
  "retryDescription": "Tu prueba aún no está confirmada. Inténtalo de nuevo; esto no reiniciará ni ampliará una prueba ya utilizada.",
  "busy": "Comprobando…",
  "retry": "Intentar de nuevo",
  "verificationError": "No hemos podido verificar tu conexión. Inténtalo de nuevo o vuelve a abrir la app desde Shopify."
};
const he: Copy = {
  "checking": "בודקים את חיבור Shopify ואת תקופת הניסיון שלך…",
  "trialActive": "תקופת הניסיון שלך ל-14 יום ב-Pro + AI פעילה",
  "workspaceReady": "סביבת העבודה שלך ב-WhachatCRM מוכנה",
  "choosePlan": "בחרו תוכנית כדי להמשיך",
  "reconnect": "פתחו מחדש את WhachatCRM מתוך Shopify",
  "eligibility": "צריך לבדוק את זכאות החנות לתקופת ניסיון",
  "notActive": "עדיין לא הצלחנו להפעיל את תקופת הניסיון",
  "connectDescription": "חברו WhatsApp או ערוץ הודעות אחר כדי להביא שיחות לקוחות ל-Inbox. אפשר להמשיך להשתמש ב-WhatsApp Business App עם WhatsApp Coexistence.",
  "trialDescription": "לא צריך לבחור תוכנית בתשלום כדי להשתמש בתקופת הניסיון הפעילה. תאריך הסיום המקורי של תקופת הניסיון נשאר ללא שינוי.",
  "connect": "חיבור ערוץ",
  "inbox": "כניסה ל-Inbox",
  "plansAnytime": "אפשר לצפות בתוכניות בכל עת",
  "noAccess": "לחנות הזו אין תקופת ניסיון פעילה או גישה בתשלום. התקנה מחדש לא מתחילה תקופת ניסיון חדשה.",
  "plans": "צפייה בתוכניות Shopify",
  "reopenDescription": "פתחו את האפליקציה מתוך ניהול Shopify כדי להתחבר מחדש. אם חזרתם מההתקנה, אפשרו עוגיות לאפליקציה ונסו לפתוח אותה שוב.",
  "admin": "פתיחת ניהול Shopify",
  "checkAgain": "בדיקת החיבור שוב",
  "supportDescription": "צריך לבדוק את היסטוריית הניסיון של החנות. לא התחלנו ולא איפסנו תקופת ניסיון.",
  "support": "יצירת קשר עם התמיכה",
  "retryDescription": "תקופת הניסיון עדיין לא אושרה. נסו שוב; הניסיון החוזר לא יאפס או יאריך תקופת ניסיון שכבר נוצלה.",
  "busy": "בודקים…",
  "retry": "ניסיון חוזר",
  "verificationError": "לא הצלחנו לאמת את החיבור. נסו שוב או פתחו מחדש את האפליקציה מתוך Shopify."
};
export function shopifyOnboardingCopy(locale = "en"): Copy {
  const language = locale.split("-")[0];
  return language === "he" ? he : language === "es" ? es : en;
}
