import { createHash } from "node:crypto";
import { safeFetchHtml } from "./competitorResearch";
export type SeoPageContent={canonicalUrl:string;title:string;metaDescription:string;headings:string[];bodyText:string;structuredData:unknown[];internalLinks:string[]};
const decode=(s:string)=>s.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
const attr=(html:string,tag:string,name:string)=>new RegExp(`<${tag}[^>]*\\b${name}=["']([^"']*)["'][^>]*>`,`i`).exec(html)?.[1]??"";
function removeSiteChrome(html:string){return html.replace(/<(nav|header|footer|aside|dialog)[^>]*>[\s\S]*?<\/\1>/gi," ").replace(/<([a-z][\w:-]*)[^>]*(?:id|class)=["'][^"']*(?:cookie|consent|navigation|site-header|site-footer)[^"']*["'][^>]*>[\s\S]*?<\/\1>/gi," ");}
/** Only semantic or explicitly declared main content is reliable enough for recommendations. */
export function extractSeoMainContent(html:string){const semantic=[...html.matchAll(/<(main|article)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(match=>match[2]);if(semantic.length)return removeSiteChrome(semantic.join(" "));const role=/<([a-z][\w:-]*)\b[^>]*role=["']main["'][^>]*>([\s\S]*?)<\/\1>/i.exec(html);return role?removeSiteChrome(role[2]):"";}
export function normalizeSeoPageContent(input:SeoPageContent):SeoPageContent{return{canonicalUrl:input.canonicalUrl.trim(),title:decode(input.title),metaDescription:decode(input.metaDescription),headings:input.headings.map(decode).filter(Boolean),bodyText:decode(input.bodyText),structuredData:input.structuredData.map(v=>sortJson(v)),internalLinks:[...new Set(input.internalLinks.map(v=>v.trim()).filter(Boolean))].sort()};}
function sortJson(value:unknown):unknown{if(Array.isArray(value))return value.map(sortJson);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sortJson(v)]));return value;}
export function parseSeoPage(html:string,pageUrl:string):SeoPageContent{const clean=html.replace(/<script(?![^>]*application\/ld\+json)[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<!--([\s\S]*?)-->/g," ");const title=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(clean)?.[1]??"";const meta=/<meta[^>]+name=["']description["'][^>]*>/i.exec(clean)?.[0]??"";const canonical=/<link[^>]+rel=["']canonical["'][^>]*>/i.exec(clean)?.[0]??"";const main=extractSeoMainContent(clean),headings=[...main.matchAll(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/gi)].map(m=>m[1]);const structured=[...html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap(m=>{try{return[JSON.parse(m[1])]}catch{return[]}});const base=new URL(pageUrl);const links=[...main.matchAll(/<a[^>]+href=["']([^"'#]+)["']/gi)].flatMap(m=>{try{const u=new URL(m[1],base);return u.origin===base.origin?[u.pathname+u.search]:[]}catch{return[]}});return normalizeSeoPageContent({canonicalUrl:attr(canonical,"link","href")||pageUrl,title,metaDescription:attr(meta,"meta","content"),headings,bodyText:main,structuredData:structured,internalLinks:links});}
export function fingerprintSeoPage(content:SeoPageContent){return createHash("sha256").update(JSON.stringify(normalizeSeoPageContent(content))).digest("hex");}
export function isSnapshotStale(original:string,current:SeoPageContent){return original!==fingerprintSeoPage(current);}
export async function captureFirstPartyPage(url:string){const fetched=await safeFetchHtml(url);const content=parseSeoPage(fetched.html,fetched.url);return{content,fingerprint:fingerprintSeoPage(content)};}
