import { aiProvider } from "../aiProvider";

export type QueryIntent="comparison"|"alternative"|"commercial"|"informational"|"branded"|"feature_product"|"integration"|"pricing";
export type MetaPageEvidence={pageUrl?:string;title:string;currentMeta:string;headings:string[];bodyText:string;pageType?:string;queryCluster:string[];fingerprint:string;metrics:{clicks:number;impressions:number;position:number;ctr?:number};otherPageMetas?:string[]};
export type MetaEvidencePacket={pageUrl:string;pageTitle:string;h1:string;importantHeadings:string[];currentMetaDescription:string;pageType:string;searchIntent:QueryIntent;searchConsole:{queryCluster:string[];clicks:number;impressions:number;ctr:number;averagePosition:number};firstPartyFacts:string[];supportedPricingAndFeatures:string[];contentFingerprint:string};
export type MetaQualityScore={pageRelevance:number;queryIntentAlignment:number;naturalLanguage:number;specificity:number;usefulDifferentiation:number;factualAccuracy:number;keywordStuffingRisk:number;unsupportedClaimRisk:number;uniqueness:number;searchResultUsefulness:number;total:number};
export type MetaQualityReview={better:boolean;decision:"accept"|"no_material_improvement";intent:QueryIntent;current:MetaQualityScore;proposed:MetaQualityScore;reasons:string[]};
export type MetaGenerationAudit={provider:string;model:string;promptVersion:string;candidateCount:number;selectedCandidateIndex:number|null;reviewerScores:{index:number;score:number;better:boolean;rejectionReasons:string[]}[]};
export type MetaGenerationResult={decision:"accept"|"no_material_improvement";candidate?:string;review?:MetaQualityReview;audit:MetaGenerationAudit};
export interface MetaCopywriter { provider:string;model:string;generate(packet:MetaEvidencePacket):Promise<string[]> }

export const META_PROMPT_VERSION="seo-meta-copywriter-v1";
const words=(s:string)=>(s.toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]);
const normalized=(s:string)=>words(s).join(" ");
export function classifyQueryIntent(cluster:string[],pageTitle=""):QueryIntent{const q=`${cluster.join(" ")} ${pageTitle}`.toLowerCase();if(/\b(?:vs|versus|compare|comparison|best|top)\b/.test(q))return"comparison";if(/\balternatives?\b/.test(q))return"alternative";if(/\b(?:price|pricing|cost|plan)\b/.test(q))return"pricing";if(/\b(?:integrat(?:e|ion)|connect(?:or)?)\b/.test(q))return"integration";if(/\bwhachat(?:crm)?\b/.test(cluster.join(" ").toLowerCase()))return"branded";if(/\b(?:how|what|why|guide|learn)\b/.test(q))return"informational";if(/\b(?:feature|inbox|automation|crm|whatsapp)\b/.test(q))return"feature_product";return"commercial";}

const forbidden=/\b(?:grounded in the page|based on the page|the page covers|choose the right next step|explore whachatcrm|organize conversations|follow up consistently|manage customer relationships|all[- ]in[- ]one solution|take your business to the next level)\b/i;
const vague=/\b(?:explore|learn|discover)\b/i;
const unsupported=/\b(?:guarantee(?:d)?|#\s*1|number one|best in the world|100\s*%|double (?:your|their) (?:sales|revenue)|trusted by \d+)\b/i;
const featureTerms=["shopify","ai","automation","omnichannel","instagram","messenger","gmail","email","sms","team collaboration","shared inbox","unlimited users","free plan","message markup","chatbot","whatsapp"];
const stop=new Set(["with","from","that","this","your","their","page","best","compare","whachatcrm","wati","whatsapp","crm","business","teams","team"]);
function differentiators(s:string){const n=normalized(s),features=featureTerms.filter(x=>n.includes(x));const concrete=(s.match(/(?:\$\s?\d+(?:\.\d+)?(?:\s*\/\s*mo)?|\b\d+%|\bzero\b|\bfree plan\b)/gi)??[]).map(normalized);return new Set([...features,...concrete]);}
function unsupportedFacts(description:string,e:MetaPageEvidence){const evidence=normalized(`${e.title} ${e.currentMeta} ${e.headings.join(" ")} ${e.bodyText}`),bad:string[]=[];for(const term of featureTerms)if(normalized(description).includes(term)&&!evidence.includes(term))bad.push(term);for(const claim of description.match(/\$\s?\d+(?:\.\d+)?(?:\s*\/\s*mo)?|\b\d+%/gi)??[])if(!evidence.includes(normalized(claim)))bad.push(claim);return bad;}
function score(description:string,e:MetaPageEvidence,intent:QueryIntent,isProposal:boolean){
 const reasons:string[]=[],text=normalized(description),page=normalized(`${e.title} ${e.headings.join(" ")}`),queryTerms=[...new Set(e.queryCluster.flatMap(words).filter(w=>w.length>2&&!stop.has(w)))],overlap=queryTerms.filter(w=>text.includes(w)).length;
 const rawQuery=e.queryCluster.some(q=>new RegExp(`\\bfor\\s+${normalized(q).replace(/ /g,"\\s+")}\\b`,"i").test(description));
 if(description.length<70||description.length>165)reasons.push("description_length");if(rawQuery)reasons.push("awkward_raw_query");if(forbidden.test(description))reasons.push("generic_copy","generic_or_internal_copy");if(unsupported.test(description))reasons.push("unsupported_claim");
 if(!words(e.title).filter(w=>w.length>3&&!stop.has(w)).some(w=>text.includes(w))&&overlap===0)reasons.push("missing_page_topic");if(/[,:;\-–—]\s*$/.test(description)||/\.{3}$/.test(description))reasons.push("broken_or_truncated");if(e.otherPageMetas?.some(meta=>normalized(meta)===text))reasons.push("duplicate_meta");
 const stuffing=[...new Set(e.queryCluster.flatMap(words).filter(w=>w.length>2&&!['the','for','with'].includes(w)))].some(w=>(text.match(new RegExp(`\\b${w}\\b`,"g"))??[]).length>2);if(stuffing)reasons.push("keyword_stuffing");if(isProposal)for(const fact of unsupportedFacts(description,e))reasons.push(`unsupported_fact:${fact}`);
 const diff=differentiators(description).size,specificity=Math.min(10,3+overlap+diff),intentAligned=intent==="comparison"? /\b(?:compare|versus|vs\.?|differences?|pricing)\b/i.test(description):intent==="pricing"?/\b(?:price|pricing|plans?|cost)\b/i.test(description):intent==="alternative"?/\balternatives?\b/i.test(description):overlap>0;
 const values={pageRelevance:Math.min(10,4+overlap),queryIntentAlignment:intentAligned?9:4,naturalLanguage:rawQuery||forbidden.test(description)?2:vague.test(description)?6:9,specificity,usefulDifferentiation:Math.min(10,2+diff*2),factualAccuracy:reasons.some(r=>r.startsWith("unsupported"))?1:10,keywordStuffingRisk:stuffing?2:10,unsupportedClaimRisk:reasons.some(r=>r.startsWith("unsupported"))?1:10,uniqueness:reasons.includes("duplicate_meta")?0:9,searchResultUsefulness:forbidden.test(description)?2:Math.min(10,4+specificity/2)};
 return{score:{...values,total:Object.values(values).reduce((a,b)=>a+b,0)},reasons};
}
export function reviewMetaDescription(current:string,proposed:string,evidence:MetaPageEvidence):MetaQualityReview{const intent=classifyQueryIntent(evidence.queryCluster,evidence.title),a=score(current,evidence,intent,false),b=score(proposed,evidence,intent,true),currentDiff=differentiators(current),proposedDiff=differentiators(proposed);if(b.score.specificity<a.score.specificity)b.reasons.push("less_specific_than_current");if([...currentDiff].some(x=>!proposedDiff.has(x)))b.reasons.push("removes_existing_differentiators");const better=b.reasons.length===0&&b.score.total>=a.score.total+5;return{better,decision:better?"accept":"no_material_improvement",intent,current:a.score,proposed:b.score,reasons:better?[]:[...new Set(b.reasons.length?b.reasons:["quality_gain_below_threshold"])]};}

export function buildMetaEvidencePacket(e:MetaPageEvidence):MetaEvidencePacket{const headings=e.headings.map(x=>x.trim()).filter(Boolean),sentences=e.bodyText.split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>=15&&x.length<=240).slice(0,20),facts=[...new Set([...headings,...sentences])].slice(0,30);return{pageUrl:e.pageUrl??"",pageTitle:e.title,h1:headings[0]??"",importantHeadings:headings.slice(1,12),currentMetaDescription:e.currentMeta,pageType:e.pageType??"unknown",searchIntent:classifyQueryIntent(e.queryCluster,e.title),searchConsole:{queryCluster:e.queryCluster,clicks:e.metrics.clicks,impressions:e.metrics.impressions,ctr:e.metrics.ctr??(e.metrics.impressions?e.metrics.clicks/e.metrics.impressions:0),averagePosition:e.metrics.position},firstPartyFacts:facts,supportedPricingAndFeatures:facts.filter(x=>/\$|price|plan|free|feature|inbox|automation|user|markup/i.test(x)),contentFingerprint:e.fingerprint};}
const systemPrompt=`You are a senior SEO copywriter. Return JSON {"candidates":[3 to 5 strings]}. Write natural, polished, customer-facing snippets specific to the supplied evidence. Preserve useful concrete differentiators in the current meta. Never invent features, prices, competitor facts, guarantees, or superiority. Do not copy competitor wording. Avoid keyword stuffing, awkward exact-query insertion, generic CRM filler, internal SEO language, and the phrases "grounded in the page", "based on the page", "the page covers", and "choose the right next step". Aim for 140–160 characters when natural. For comparison or alternative pages, state concrete comparison value and avoid vague explore/learn/discover filler. Use only facts in the packet.`;
export class ExistingAiMetaCopywriter implements MetaCopywriter{provider:string;model:string;constructor(){const c=aiProvider.getModelConfig("automation");this.provider=c.provider;this.model=c.model;}async generate(packet:MetaEvidencePacket){const raw=await aiProvider.complete("automation",[{role:"system",content:systemPrompt},{role:"user",content:JSON.stringify(packet)}],{jsonMode:true,maxTokens:700});const parsed=JSON.parse(typeof raw==="string"?raw:raw.content) as {candidates?:unknown};if(!Array.isArray(parsed.candidates))throw new Error("Invalid meta candidate response");return parsed.candidates.filter((x):x is string=>typeof x==="string").map(x=>x.trim()).filter(Boolean).slice(0,5);}}
export async function generateAndSelectMeta(e:MetaPageEvidence,copywriter:MetaCopywriter=new ExistingAiMetaCopywriter()):Promise<MetaGenerationResult>{const base:MetaGenerationAudit={provider:copywriter.provider,model:copywriter.model,promptVersion:META_PROMPT_VERSION,candidateCount:0,selectedCandidateIndex:null,reviewerScores:[]};const current=score(e.currentMeta,e,classifyQueryIntent(e.queryCluster,e.title),false);if(e.currentMeta&&current.reasons.length===0&&current.score.total>=82)return{decision:"no_material_improvement",audit:base};try{const candidates=(await copywriter.generate(buildMetaEvidencePacket(e))).slice(0,5);base.candidateCount=candidates.length;let winner:{candidate:string;review:MetaQualityReview;index:number}|undefined;candidates.forEach((candidate,index)=>{const review=reviewMetaDescription(e.currentMeta,candidate,e);base.reviewerScores.push({index,score:review.proposed.total,better:review.better,rejectionReasons:review.reasons});if(review.better&&(!winner||review.proposed.total>winner.review.proposed.total))winner={candidate,review,index};});if(!winner)return{decision:"no_material_improvement",audit:base};base.selectedCandidateIndex=winner.index;return{decision:"accept",candidate:winner.candidate,review:winner.review,audit:base};}catch(error){base.reviewerScores.push({index:-1,score:0,better:false,rejectionReasons:["ai_provider_failure"]});return{decision:"no_material_improvement",audit:base};}}
