import { createHash } from "node:crypto";
import type { SeoMetricRow } from "./opportunities";

export type AggregateMetrics={clicks:number;impressions:number;ctr:number;position:number};
export type PageEvidence={page:string;urls:string[];current:AggregateMetrics;previous:AggregateMetrics};
export type ScoredOpportunity={clusterKey:string;queryCluster:string[];targetPage:string|null;recommendedPrimaryPage:string|null;competingPages:PageEvidence[];type:"striking_distance"|"low_ctr"|"decline"|"cannibalization";current:AggregateMetrics;previous:AggregateMetrics;priorityScore:number;confidenceScore:number;estimatedUpside:number;reason:string;evidence:Record<string,unknown>};
export type OpportunityScoringConfig={minImpressions:number;maxPerRun:number;commercialTerms:string[];lowCtrRatio:number;declineRetainedRatio:number;declinePositionDelta:number;cannibalizationMinPageImpressions:number;cannibalizationMinPageShare:number};
export const DEFAULT_OPPORTUNITY_CONFIG:OpportunityScoringConfig={minImpressions:50,maxPerRun:10,commercialTerms:["crm","software","pricing","automation","platform","tool","business"],lowCtrRatio:.6,declineRetainedRatio:.8,declinePositionDelta:2,cannibalizationMinPageImpressions:50,cannibalizationMinPageShare:.1};
/** Keep every non-trivial query term; English stopword lists erase short entities and do not generalize across languages. */
const tokens=(q:string)=>new Set(q.toLocaleLowerCase().split(/[^\p{L}\p{N}]+/u).filter(w=>[...w].length>1));
/** Shared category words alone must never drive page-consolidation advice. */
export const hasMatchingQueryIntent=(a:string,b:string)=>{const x=tokens(a),y=tokens(b);return x.size>0&&x.size===y.size&&[...x].every(token=>y.has(token));};
const aggregate=(rows:SeoMetricRow[]):AggregateMetrics=>{const impressions=rows.reduce((n,r)=>n+r.impressions,0),clicks=rows.reduce((n,r)=>n+r.clicks,0);return{clicks,impressions,ctr:clicks/Math.max(1,impressions),position:rows.reduce((n,r)=>n+r.position*r.impressions,0)/Math.max(1,impressions)}};
const expectedCtr=(position:number)=>position<=3?.12:position<=10?.04:.015;
export function materiallyCompetingPages(pages:PageEvidence[],clusterImpressions:number,config:Pick<OpportunityScoringConfig,"cannibalizationMinPageImpressions"|"cannibalizationMinPageShare">=DEFAULT_OPPORTUNITY_CONFIG){const denominator=Math.max(1,clusterImpressions);return pages.filter(page=>page.current.impressions>=config.cannibalizationMinPageImpressions||page.current.impressions/denominator>=config.cannibalizationMinPageShare);}
/** Re-check the diagnostic source collection at the action boundary; derived competingPages alone is not trusted. */
export function hasMaterialCannibalizationEvidence(item:ScoredOpportunity,config:Pick<OpportunityScoringConfig,"cannibalizationMinPageImpressions"|"cannibalizationMinPageShare">=DEFAULT_OPPORTUNITY_CONFIG){const visible=Array.isArray(item.evidence.currentVisiblePages)?item.evidence.currentVisiblePages as PageEvidence[]:[];const material=materiallyCompetingPages(visible,item.current.impressions,config);return material.length>=2&&item.competingPages.length>=2&&item.competingPages.every(page=>material.some(candidate=>candidate.page===page.page));}
export function normalizeSeoPageIdentity(raw:string){try{const value=raw.trim();if(!value)return "";const absolute=/^[a-z][a-z\d+.-]*:\/\//i.test(value),url=new URL(value,"https://seo-normalization.invalid");url.hash="";url.hostname=url.hostname.toLowerCase();for(const key of [...url.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(key))url.searchParams.delete(key);url.searchParams.sort();if(url.pathname!=="/")url.pathname=url.pathname.replace(/\/+$/,"");return absolute?url.toString():`${url.pathname}${url.search}`;}catch{return raw.trim().replace(/\/+$/,"");}}
type NormalizedMetricRow=SeoMetricRow&{sourceQueries:string[];sourcePages:string[]};
/** Combines casing and harmless URL variants; position is impression-weighted and falls back to 0 when no impressions exist. */
export function aggregateNormalizedMetricRows(rows:SeoMetricRow[]):NormalizedMetricRow[]{const grouped=new Map<string,{query:string;page:string;clicks:number;impressions:number;weightedPosition:number;sourceQueries:Set<string>;sourcePages:Set<string>}>();for(const row of rows){const query=row.query.trim().toLowerCase(),page=normalizeSeoPageIdentity(row.page),key=`${query}\0${page}`,existing=grouped.get(key)??{query,page,clicks:0,impressions:0,weightedPosition:0,sourceQueries:new Set<string>(),sourcePages:new Set<string>()};existing.clicks+=row.clicks;existing.impressions+=row.impressions;existing.weightedPosition+=row.position*row.impressions;existing.sourceQueries.add(row.query);existing.sourcePages.add(row.page);grouped.set(key,existing);}return[...grouped.values()].map(row=>({query:row.query,page:row.page,clicks:row.clicks,impressions:row.impressions,position:row.impressions>0?row.weightedPosition/row.impressions:0,sourceQueries:[...row.sourceQueries].sort(),sourcePages:[...row.sourcePages].sort()})).sort((a,b)=>identity(a).localeCompare(identity(b)));}
const rankPages=(current:NormalizedMetricRow[],previous:NormalizedMetricRow[])=>{const identities=[...new Set([...current,...previous].map(r=>r.page))];return identities.map(page=>{const matches=(rows:NormalizedMetricRow[])=>rows.filter(r=>r.page===page),cur=matches(current),old=matches(previous);return{page,urls:[...new Set([...cur,...old].flatMap(r=>r.sourcePages))].sort(),current:aggregate(cur),previous:aggregate(old)}}).sort((a,b)=>b.current.clicks-a.current.clicks||b.current.impressions-a.current.impressions||a.current.position-b.current.position||b.previous.clicks-a.previous.clicks||b.previous.impressions-a.previous.impressions||a.page.localeCompare(b.page));};
const selectPrimaryPage=(pages:PageEvidence[])=>{const first=pages[0],second=pages[1];if(!first)return null;if(!second)return first.page;const score=(p:PageEvidence)=>[p.current.clicks,p.current.impressions,-p.current.position,p.previous.clicks,p.previous.impressions];const a=score(first),b=score(second);return a.some((value,index)=>value!==b[index])?first.page:null;};
const identity=(r:SeoMetricRow)=>`${r.query.trim().toLowerCase()}\0${normalizeSeoPageIdentity(r.page)}`;
/** Inputs must already be SQL-bounded in production; this union logic also makes prior-only losses testable and deterministic. */
export function clusterAndScoreOpportunities(current:SeoMetricRow[],previous:SeoMetricRow[],config=DEFAULT_OPPORTUNITY_CONFIG):ScoredOpportunity[]{
 const normalizedCurrent=aggregateNormalizedMetricRows(current),normalizedPrevious=aggregateNormalizedMetricRows(previous),currentByKey=new Map(normalizedCurrent.map(r=>[identity(r),r])),previousByKey=new Map(normalizedPrevious.map(r=>[identity(r),r]));
 const currentPagesByQuery=new Map<string,Set<string>>();for(const row of normalizedCurrent)if(row.impressions>0){const pages=currentPagesByQuery.get(row.query)??new Set<string>();pages.add(row.page);currentPagesByQuery.set(row.query,pages);}
 const seeds=[...new Set([...currentByKey.keys(),...previousByKey.keys()])].map(key=>{const cur=currentByKey.get(key),old=previousByKey.get(key);return{key,query:(cur??old)!.query,page:(cur??old)!.page,current:cur,previous:old,volume:Math.max(cur?.impressions??0,old?.impressions??0)}}).filter(seed=>{
  const cur=seed.current??{clicks:0,impressions:0,position:0},old=seed.previous??{clicks:0,impressions:0,position:0};const decline=old.impressions>=config.minImpressions&&((old.clicks>0&&cur.clicks<=old.clicks*config.declineRetainedRatio)||cur.impressions<=old.impressions*config.declineRetainedRatio||(cur.impressions>0&&cur.position>old.position+config.declinePositionDelta));const lowCtr=cur.impressions>=config.minImpressions&&cur.clicks/cur.impressions<expectedCtr(cur.position)*config.lowCtrRatio;return (currentPagesByQuery.get(seed.query.trim().toLowerCase())?.size??0)>1||decline||(cur.impressions>=config.minImpressions&&(lowCtr||(cur.position>=4&&cur.position<=20)));
 }).sort((a,b)=>b.volume-a.volume||a.key.localeCompare(b.key));
 const pending=[...seeds],out:ScoredOpportunity[]=[];
 while(pending.length){const seed=pending.shift()!,cluster=[seed,...pending.filter(r=>hasMatchingQueryIntent(seed.query,r.query))];for(const r of cluster.slice(1)){const i=pending.indexOf(r);if(i>=0)pending.splice(i,1);}const queries=[...new Set(cluster.map(r=>r.query))].sort(),curRows=cluster.map(r=>r.current??{query:r.query,page:r.page,clicks:0,impressions:0,position:0,sourceQueries:[r.query],sourcePages:[r.page]}),oldRows=cluster.map(r=>r.previous??{query:r.query,page:r.page,clicks:0,impressions:0,position:0,sourceQueries:[r.query],sourcePages:[r.page]}),cur=aggregate(curRows),old=aggregate(oldRows),allEvidencePages=rankPages(curRows.filter(r=>r.impressions>0),oldRows.filter(r=>r.impressions>0)),currentVisiblePages=rankPages(curRows.filter(r=>r.impressions>0),[]),materialPageIds=new Set(materiallyCompetingPages(currentVisiblePages,cur.impressions,config).map(page=>page.page)),materialCurrentPages=allEvidencePages.filter(page=>materialPageIds.has(page.page)),hasMaterialCompetition=materialCurrentPages.length>1,previousVisiblePages=rankPages([],oldRows.filter(r=>r.impressions>0)),historicalPages=previousVisiblePages.filter(page=>!currentVisiblePages.some(currentPage=>currentPage.page===page.page)),recommendedPrimaryPage=selectPrimaryPage(materialCurrentPages.length?materialCurrentPages:currentVisiblePages),targetPage=(recommendedPrimaryPage??materialCurrentPages[0]?.page??currentVisiblePages[0]?.page??allEvidencePages[0]?.page)||null,expected=expectedCtr(cur.position),lowCtr=cur.impressions>=config.minImpressions&&cur.ctr<expected*config.lowCtrRatio,decline=old.impressions>=config.minImpressions&&((old.clicks>0&&cur.clicks<=old.clicks*config.declineRetainedRatio)||cur.impressions<=old.impressions*config.declineRetainedRatio||(cur.impressions>0&&cur.position>old.position+config.declinePositionDelta)),striking=cur.impressions>=config.minImpressions&&cur.position>=4&&cur.position<=20;
  const type=hasMaterialCompetition?"cannibalization":decline?"decline":striking?"striking_distance":lowCtr?"low_ctr":null;if(!type)continue;const commercial=queries.some(q=>config.commercialTerms.some(t=>q.toLowerCase().includes(t))),loss=Math.max(0,old.clicks-cur.clicks)+Math.max(0,(old.impressions-cur.impressions)*.02),upside=Math.max(0,(expected-cur.ctr)*cur.impressions),priority=Math.round(Math.min(100,Math.log10(Math.max(cur.impressions,old.impressions)+1)*15+upside*2+loss+(commercial?15:0))),normalizedPage=targetPage??"__no_safe_primary__";
  out.push({clusterKey:createHash("sha256").update(`${normalizedPage}\0${queries.map(q=>q.toLowerCase()).join("\0")}`).digest("hex"),queryCluster:queries,targetPage,recommendedPrimaryPage,competingPages:hasMaterialCompetition?materialCurrentPages:allEvidencePages,type,current:cur,previous:old,priorityScore:priority,confidenceScore:Number(Math.min(.95,.45+Math.log10(Math.max(cur.impressions,old.impressions)+1)/10+(old.impressions?0.1:0)).toFixed(2)),estimatedUpside:Number(upside.toFixed(1)),reason:type==="decline"?`Traffic declined from ${old.impressions} to ${cur.impressions} impressions.`:hasMaterialCompetition?`Possible cannibalization across ${materialCurrentPages.length} currently visible pages with material query evidence; primary selected by clicks, impressions, position, then URL.`:`${type.replaceAll("_"," ")} cluster with ${cur.impressions} impressions${commercial?" and commercial intent":""}.`,evidence:{expectedCtr:expected,lowCtrThreshold:expected*config.lowCtrRatio,queryCount:queries.length,commercialIntent:commercial,competingPages:materialCurrentPages,currentVisiblePages,materialCurrentPages,cannibalizationThresholds:{minPageImpressions:config.cannibalizationMinPageImpressions,minPageShare:config.cannibalizationMinPageShare,clusterImpressions:cur.impressions},previousVisiblePages,historicalPages,allEvidencePages,recommendedPrimaryPage,decline:{qualifies:decline,current:cur,previous:old}}});
 }
 return out.sort((a,b)=>b.priorityScore-a.priorityScore||a.clusterKey.localeCompare(b.clusterKey)).slice(0,config.maxPerRun);
}
export function excludeOpenActionCandidates<T extends {key:string}>(ranked:T[],openKeys:ReadonlySet<string>){return{eligible:ranked.filter(row=>!openKeys.has(row.key)),excluded:ranked.filter(row=>openKeys.has(row.key)).length};}
export function selectCompleteQueryGroups<T extends {rowCount:number}>(ranked:T[],rowLimit:number){let used=0;const selected:T[]=[];for(const group of ranked){const size=Math.max(0,Math.floor(group.rowCount));if(used+size>rowLimit)continue;selected.push(group);used+=size;}return{selected,used};}
/** Runs bounded successful work while isolating a malformed candidate from the rest of the ranked pool. */
export async function processCandidatesUntil<T>(candidates:T[],successLimit:number,work:(candidate:T)=>Promise<boolean>,onFailure:(error:unknown)=>void){let successes=0,attempted=0;for(const candidate of candidates){if(successes>=successLimit)break;attempted++;try{if(await work(candidate))successes++;}catch(error){onFailure(error);}}return{successes,attempted};}
