import { createHash } from "node:crypto";
import type { SeoMetricRow } from "./opportunities";

export type AggregateMetrics={clicks:number;impressions:number;ctr:number;position:number};
export type PageEvidence=AggregateMetrics&{page:string};
export type ScoredOpportunity={clusterKey:string;queryCluster:string[];targetPage:string|null;competingPages:PageEvidence[];type:"striking_distance"|"low_ctr"|"decline"|"cannibalization";current:AggregateMetrics;previous:AggregateMetrics;priorityScore:number;confidenceScore:number;estimatedUpside:number;reason:string;evidence:Record<string,unknown>};
export type OpportunityScoringConfig={minImpressions:number;maxPerRun:number;commercialTerms:string[];lowCtrRatio:number;declineRetainedRatio:number;declinePositionDelta:number};
export const DEFAULT_OPPORTUNITY_CONFIG:OpportunityScoringConfig={minImpressions:50,maxPerRun:10,commercialTerms:["crm","software","pricing","automation","platform","tool","business"],lowCtrRatio:.6,declineRetainedRatio:.8,declinePositionDelta:2};
const tokens=(q:string)=>new Set(q.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>2));
const similarity=(a:string,b:string)=>{const x=tokens(a),y=tokens(b),common=[...x].filter(t=>y.has(t)).length;return common/Math.max(1,Math.min(x.size,y.size));};
const aggregate=(rows:SeoMetricRow[]):AggregateMetrics=>{const impressions=rows.reduce((n,r)=>n+r.impressions,0),clicks=rows.reduce((n,r)=>n+r.clicks,0);return{clicks,impressions,ctr:clicks/Math.max(1,impressions),position:rows.reduce((n,r)=>n+r.position*r.impressions,0)/Math.max(1,impressions)}};
const expectedCtr=(position:number)=>position<=3?.12:position<=10?.04:.015;
const rankPages=(rows:SeoMetricRow[])=>[...new Set(rows.map(r=>r.page))].map(page=>({page,...aggregate(rows.filter(r=>r.page===page))})).sort((a,b)=>b.clicks-a.clicks||b.impressions-a.impressions||a.position-b.position||a.page.localeCompare(b.page));
const identity=(r:SeoMetricRow)=>`${r.query.trim().toLowerCase()}\0${r.page}`;
/** Inputs must already be SQL-bounded in production; this union logic also makes prior-only losses testable and deterministic. */
export function clusterAndScoreOpportunities(current:SeoMetricRow[],previous:SeoMetricRow[],config=DEFAULT_OPPORTUNITY_CONFIG):ScoredOpportunity[]{
 const currentByKey=new Map(current.map(r=>[identity(r),r])),previousByKey=new Map(previous.map(r=>[identity(r),r]));
 const seeds=[...new Set([...currentByKey.keys(),...previousByKey.keys()])].map(key=>{const cur=currentByKey.get(key),old=previousByKey.get(key);return{key,query:(cur??old)!.query,page:(cur??old)!.page,current:cur,previous:old,volume:Math.max(cur?.impressions??0,old?.impressions??0)}}).filter(seed=>{
  const cur=seed.current??{clicks:0,impressions:0,position:0},old=seed.previous??{clicks:0,impressions:0,position:0};const decline=old.impressions>=config.minImpressions&&((old.clicks>0&&cur.clicks<=old.clicks*config.declineRetainedRatio)||cur.impressions<=old.impressions*config.declineRetainedRatio||(cur.impressions>0&&cur.position>old.position+config.declinePositionDelta));const lowCtr=cur.impressions>=config.minImpressions&&cur.clicks/cur.impressions<expectedCtr(cur.position)*config.lowCtrRatio;return decline||(cur.impressions>=config.minImpressions&&(lowCtr||(cur.position>=4&&cur.position<=20)));
 }).sort((a,b)=>b.volume-a.volume||a.key.localeCompare(b.key));
 const pending=[...seeds],out:ScoredOpportunity[]=[];
 while(pending.length){const seed=pending.shift()!,cluster=[seed,...pending.filter(r=>similarity(seed.query,r.query)>=.5)];for(const r of cluster.slice(1)){const i=pending.indexOf(r);if(i>=0)pending.splice(i,1);}const queries=[...new Set(cluster.map(r=>r.query))].sort(),curRows=cluster.map(r=>r.current??{query:r.query,page:r.page,clicks:0,impressions:0,position:0}),oldRows=cluster.map(r=>r.previous??{query:r.query,page:r.page,clicks:0,impressions:0,position:0}),cur=aggregate(curRows),old=aggregate(oldRows),pageBasis=cur.impressions>0?curRows.filter(r=>r.impressions>0):oldRows.filter(r=>r.impressions>0),pages=rankPages(pageBasis),targetPage=pages[0]?.page||null,expected=expectedCtr(cur.position),lowCtr=cur.impressions>=config.minImpressions&&cur.ctr<expected*config.lowCtrRatio,decline=old.impressions>=config.minImpressions&&((old.clicks>0&&cur.clicks<=old.clicks*config.declineRetainedRatio)||cur.impressions<=old.impressions*config.declineRetainedRatio||(cur.impressions>0&&cur.position>old.position+config.declinePositionDelta)),striking=cur.impressions>=config.minImpressions&&cur.position>=4&&cur.position<=20;
  const type=decline?"decline":pages.length>1?"cannibalization":striking?"striking_distance":lowCtr?"low_ctr":null;if(!type)continue;const commercial=queries.some(q=>config.commercialTerms.some(t=>q.toLowerCase().includes(t))),loss=Math.max(0,old.clicks-cur.clicks)+Math.max(0,(old.impressions-cur.impressions)*.02),upside=Math.max(0,(expected-cur.ctr)*cur.impressions),priority=Math.round(Math.min(100,Math.log10(Math.max(cur.impressions,old.impressions)+1)*15+upside*2+loss+(commercial?15:0))),normalizedPage=targetPage??"__no_safe_primary__";
  out.push({clusterKey:createHash("sha256").update(`${normalizedPage}\0${queries.map(q=>q.toLowerCase()).join("\0")}`).digest("hex"),queryCluster:queries,targetPage,competingPages:pages,type,current:cur,previous:old,priorityScore:priority,confidenceScore:Number(Math.min(.95,.45+Math.log10(Math.max(cur.impressions,old.impressions)+1)/10+(old.impressions?0.1:0)).toFixed(2)),estimatedUpside:Number(upside.toFixed(1)),reason:type==="decline"?`Traffic declined from ${old.impressions} to ${cur.impressions} impressions.`:pages.length>1?`Possible cannibalization across ${pages.length} pages; primary selected by clicks, impressions, position, then URL.`:`${type.replaceAll("_"," ")} cluster with ${cur.impressions} impressions${commercial?" and commercial intent":""}.`,evidence:{expectedCtr:expected,lowCtrThreshold:expected*config.lowCtrRatio,queryCount:queries.length,commercialIntent:commercial,competingPages:pages}});
 }
 return out.sort((a,b)=>b.priorityScore-a.priorityScore||a.clusterKey.localeCompare(b.clusterKey)).slice(0,config.maxPerRun);
}
