import { createHash } from "node:crypto";
import type { SeoMetricRow } from "./opportunities";

export type AggregateMetrics={clicks:number;impressions:number;ctr:number;position:number};
export type PageEvidence=AggregateMetrics&{page:string};
export type ScoredOpportunity={clusterKey:string;queryCluster:string[];targetPage:string|null;competingPages:PageEvidence[];type:"striking_distance"|"low_ctr"|"decline"|"cannibalization";current:AggregateMetrics;previous:AggregateMetrics;priorityScore:number;confidenceScore:number;estimatedUpside:number;reason:string;evidence:Record<string,unknown>};
export type OpportunityScoringConfig={minImpressions:number;maxPerRun:number;commercialTerms:string[]};
export const DEFAULT_OPPORTUNITY_CONFIG:OpportunityScoringConfig={minImpressions:50,maxPerRun:10,commercialTerms:["crm","software","pricing","automation","platform","tool","business"]};
const tokens=(q:string)=>new Set(q.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(w=>w.length>2));
const similarity=(a:string,b:string)=>{const x=tokens(a),y=tokens(b);const common=[...x].filter(t=>y.has(t)).length;return common/Math.max(1,Math.min(x.size,y.size));};
const aggregate=(rows:SeoMetricRow[]):AggregateMetrics=>{const impressions=rows.reduce((n,r)=>n+r.impressions,0),clicks=rows.reduce((n,r)=>n+r.clicks,0);return{clicks,impressions,ctr:clicks/Math.max(1,impressions),position:rows.reduce((n,r)=>n+r.position*r.impressions,0)/Math.max(1,impressions)}};
const rankPages=(rows:SeoMetricRow[])=>[...new Set(rows.map(r=>r.page))].map(page=>({page,...aggregate(rows.filter(r=>r.page===page))})).sort((a,b)=>b.clicks-a.clicks||b.impressions-a.impressions||a.position-b.position||a.page.localeCompare(b.page));
/** Clusters related queries first, then selects a deterministic primary page. Null means no page has usable evidence. */
export function clusterAndScoreOpportunities(current:SeoMetricRow[],previous:SeoMetricRow[],config=DEFAULT_OPPORTUNITY_CONFIG):ScoredOpportunity[]{
 const eligible=current.filter(r=>r.impressions>=config.minImpressions),pending=[...eligible].sort((a,b)=>b.impressions-a.impressions||a.query.localeCompare(b.query)),out:ScoredOpportunity[]=[];
 while(pending.length){const seed=pending.shift()!,clusterRows=[seed,...pending.filter(r=>similarity(seed.query,r.query)>=.5)];for(const r of clusterRows.slice(1)){const i=pending.indexOf(r);if(i>=0)pending.splice(i,1);}const queries=[...new Set(clusterRows.map(r=>r.query))].sort();const pages=rankPages(clusterRows);const targetPage=pages[0]?.impressions>0?pages[0].page:null;
  const oldRows=previous.filter(r=>queries.some(q=>similarity(q,r.query)>=.5)&&(targetPage===null||clusterRows.some(c=>c.page===r.page)));const cur=aggregate(clusterRows),old=aggregate(oldRows),commercial=queries.some(q=>config.commercialTerms.some(t=>q.toLowerCase().includes(t)));const expected=cur.position<=3?.12:cur.position<=10?.04:.015,loss=Math.max(0,old.clicks-cur.clicks)+Math.max(0,(old.impressions-cur.impressions)*.02),upside=Math.max(0,(expected-cur.ctr)*cur.impressions);const type=pages.length>1?"cannibalization":loss>upside?"decline":cur.position>=4&&cur.position<=20?"striking_distance":"low_ctr";const priority=Math.round(Math.min(100,Math.log10(cur.impressions+1)*15+upside*2+loss+(commercial?15:0)));
  const normalizedPage=targetPage??"__no_safe_primary__";out.push({clusterKey:createHash("sha256").update(`${normalizedPage}\0${queries.map(q=>q.toLowerCase()).join("\0")}`).digest("hex"),queryCluster:queries,targetPage,competingPages:pages,type,current:cur,previous:old,priorityScore:priority,confidenceScore:Number(Math.min(.95,.45+Math.log10(cur.impressions+1)/10+(old.impressions?0.1:0)).toFixed(2)),estimatedUpside:Number(upside.toFixed(1)),reason:pages.length>1?`Possible cannibalization across ${pages.length} pages; primary selected by clicks, impressions, position, then URL.`:`${type.replaceAll("_"," ")} cluster with ${cur.impressions} impressions${commercial?" and commercial intent":""}.`,evidence:{expectedCtr:expected,queryCount:queries.length,commercialIntent:commercial,competingPages:pages}});
 }
 return out.sort((a,b)=>b.priorityScore-a.priorityScore||a.clusterKey.localeCompare(b.clusterKey)).slice(0,config.maxPerRun);
}
