import assert from "node:assert/strict";
import { buildProposal, InsufficientSeoEvidenceError, normalizeActionListInput, seoActionViewStatuses, storedProposalReviewability, seoActionRefreshDisposition, recoveredRefreshStatus } from "../server/seo/actionService";
import { mayTransitionSeoAction, validateRecommendationOutput } from "../server/seo/actionPlanner";
import { buildImplementationBrief, implementationBriefEligibility, type SeoAction } from "../client/src/components/admin/SeoActionsPanel";
import type { ScoredOpportunity } from "../server/seo/opportunityPlanner";

assert.deepEqual(seoActionViewStatuses("review"),["proposed","revision_required","researching"]);
assert.deepEqual(seoActionViewStatuses("approved"),["approved"]);
assert.ok(seoActionViewStatuses("history").includes("rejected"));
assert.deepEqual(normalizeActionListInput({view:"bogus",search:"  zoko ",page:-4,limit:999}),{view:"review",search:"zoko",type:undefined,page:1,limit:50,offset:0});
assert.equal(normalizeActionListInput({view:"history",page:3,limit:20}).offset,40);
assert.deepEqual(storedProposalReviewability({status:"proposed",proposal:{legacy:true}}),{approvalBlocked:true,invalidReason:"This proposal predates or fails the current recommendation rules"});
assert.deepEqual(storedProposalReviewability({status:"approved",proposal:{legacy:true}}),{approvalBlocked:true,invalidReason:"This proposal predates or fails the current recommendation rules"},"invalid approved history is blocked from handoff without rewriting its decision");

const item=(overrides:Partial<ScoredOpportunity>={}):ScoredOpportunity=>({clusterKey:"fixture-cluster",queryCluster:["real estate crm follow up"],targetPage:"https://whachatcrm.com/real-estate-crm",recommendedPrimaryPage:"https://whachatcrm.com/real-estate-crm",competingPages:[],type:"low_ctr",current:{clicks:2,impressions:113,ctr:2/113,position:8},previous:{clicks:3,impressions:100,ctr:.03,position:7},priorityScore:80,confidenceScore:.7,estimatedUpside:2.5,reason:"CTR is below the documented threshold at a first-page average position.",evidence:{},...overrides});
const snapshot={fingerprint:"a".repeat(64),title:"Real Estate CRM | WhachatCRM",metaDescription:"Keep property leads organized.",headings:["Real Estate CRM","Follow up with every property lead"],sections:["Capture property inquiries from WhatsApp, assign leads to agents, and track follow-up in one shared inbox."],competitorCount:0};
const proposal=buildProposal(item(),snapshot);
assert.equal(proposal.actionType,"meta_description");assert.equal(proposal.insertionLocation,"Replace meta description");assert.equal(proposal.currentValue,snapshot.metaDescription);assert.match(proposal.proposedMetaDescription!,/Real Estate CRM/);assert.match(proposal.proposedMetaDescription!,/property inquiries/);assert.match(proposal.evidenceLimitations,/No competitor research/);assert.doesNotMatch(proposal.expectedBenefit,/\d+%/);assert.match(proposal.expectedBenefit,/no uplift is estimated/i);assert.equal(proposal.automaticExecutionEligible,false);
assert.throws(()=>buildProposal(item({current:{clicks:0,impressions:100,ctr:0,position:80}}),snapshot),InsufficientSeoEvidenceError,"low rank plus low CTR is not a snippet recommendation");
assert.throws(()=>buildProposal(item(),{...snapshot,title:"",sections:[]}),InsufficientSeoEvidenceError);
assert.throws(()=>validateRecommendationOutput({...proposal,proposedMetaDescription:"Explore WhachatCRM for real estate CRM: manage customer relationships in one workspace."}),/generic boilerplate/);
assert.throws(()=>validateRecommendationOutput({...proposal,proposedMetaDescription:snapshot.metaDescription}),/does not materially change/);
assert.throws(()=>validateRecommendationOutput({...proposal,proposedMetaDescription:"Guaranteed #1 real estate CRM for every agent."}),/unsupported/);
const expansion=buildProposal(item({type:"striking_distance",queryCluster:["what happens after a property inquiry arrives"],current:{clicks:4,impressions:90,ctr:4/90,position:9}}),snapshot);assert.equal(expansion.actionType,"content_expansion");assert.equal(expansion.proposedContent,"## What happens after a property inquiry arrives\n\nThe verified workflow described on this page is: Capture property inquiries from WhatsApp, assign leads to agents, and track follow-up in one shared inbox.");assert.match(expansion.insertionLocation,/Follow up with every property lead/);assert.doesNotMatch(expansion.proposedContent!,/^##[^\n]+\n\nCapture/,"draft is a grounded answer, not body text copied under a heading");
const spanish=buildProposal(item({type:"striking_distance",targetPage:"https://whachatcrm.com/es/real-estate-crm",queryCluster:["qué sucede después de una consulta inmobiliaria"]}),{...snapshot,title:"CRM inmobiliario para equipos",headings:["Gestión de consultas"],sections:["Cuando llega una consulta inmobiliaria, el equipo asigna el contacto a un agente y registra el seguimiento en la bandeja compartida."]});assert.match(spanish.proposedContent!,/^## Qué sucede después/);assert.match(spanish.proposedContent!,/El flujo verificado descrito en esta página es:/);
const hebrew=buildProposal(item({type:"striking_distance",targetPage:"https://whachatcrm.com/he/real-estate-crm",queryCluster:["מה קורה אחרי פניית נדלן חדשה"]}),{...snapshot,title:"מערכת נדלן לצוותים",headings:["טיפול בפניות"],sections:["כאשר מגיעה פניית נדלן חדשה, המערכת מקצה את הפנייה לסוכן ושומרת את המעקב בתיבה המשותפת."]});assert.match(hebrew.proposedContent!,/^## מה קורה אחרי/);assert.match(hebrew.proposedContent!,/התהליך המאומת המתואר בעמוד הוא:/);
assert.throws(()=>buildProposal(item({type:"striking_distance",queryCluster:["whatsapp crm pricing"]}),snapshot),/does not contain verified facts that answer/,"pricing cannot be inferred from routing evidence");
assert.throws(()=>buildProposal(item({type:"striking_distance",queryCluster:["property inquiries assign leads agents track follow up"]}),snapshot),InsufficientSeoEvidenceError,"covered topics do not get filler");
assert.throws(()=>buildProposal(item({type:"striking_distance",targetPage:"https://whachatcrm.com/es/real-estate-crm",queryCluster:["what happens after a property inquiry"]}),{...snapshot,title:"CRM inmobiliario para equipos",sections:["Cuando llega una consulta inmobiliaria, el equipo la asigna a un agente."]}),/does not match the target page language/);
const serviceSource=(await import("node:fs")).readFileSync(new URL("../server/seo/actionService.ts",import.meta.url),"utf8");
assert.match(serviceSource,/status IN \('detected','researching','proposed','approved','revision_required','rejected'\)/,"unchanged rejected identities remain deduplicated");
assert.match(serviceSource,/\["proposed","revision_required","rejected"\]/,"rejected records can be re-evaluated in place with history preserved");
assert.match(serviceSource,/published:false/,"approval and refresh never publish website content");
assert.match(serviceSource,/a\.property_id=\$\{propertyId\}/,"action reads are workspace scoped");
const staleApproved=seoActionRefreshDisposition({status:"approved",stale_at:"2026-09-24T00:00:00Z"});assert.deepEqual(staleApproved,{allowed:true,expired:false,returnStatus:"revision_required"},"stale approval can be re-evaluated but cannot carry approval forward");
const validApprovedProposal={...proposal};
assert.equal(seoActionRefreshDisposition({status:"approved",stale_at:null,proposal:validApprovedProposal,version_missing:false}).allowed,false,"valid unchanged approved actions cannot be rewritten");
const legacyApproved={status:"approved",stale_at:null,proposal:{legacySchema:true},version_missing:false};
assert.deepEqual(storedProposalReviewability(legacyApproved),{approvalBlocked:true,invalidReason:"This proposal predates or fails the current recommendation rules"},"listing marks a legacy approved proposal for re-evaluation");
assert.deepEqual(seoActionRefreshDisposition(legacyApproved),{allowed:true,expired:false,returnStatus:"revision_required"},"the refresh claim applies the same persisted-proposal validation as listing");
assert.deepEqual(seoActionRefreshDisposition({status:"researching",refresh_lease_expires_at:"2026-09-23T00:00:00Z",refresh_return_status:"revision_required"},new Date("2026-09-24T00:00:00Z")),{allowed:true,expired:true,returnStatus:"revision_required"});
assert.match(serviceSource,/status:"proposed"[\s\S]+approvedBy:null,approvedAt:null/,"a revised version returns to review and clears current approval fields");
assert.match(serviceSource,/LEFT JOIN seo_action_versions v[\s\S]+a\.property_id=\$\{propertyId\}[\s\S]+FOR UPDATE OF a/,"refresh eligibility is derived from the workspace-scoped persisted proposal while locking the action");
assert.match(serviceSource,/OPPORTUNITY_NO_LONGER_QUALIFIES[\s\S]+status:"revision_required"|status:"revision_required"[\s\S]+OPPORTUNITY_NO_LONGER_QUALIFIES/,"insufficient refreshed evidence remains recoverable");
assert.match(serviceSource,/status:claim\.returnStatus[\s\S]+prior proposal restored/,"refresh failure restores a retryable state and prior version");
assert.match(serviceSource,/INSUFFICIENT_EVIDENCE[\s\S]+versionCreated:false,recoverable:true/,"insufficient evidence returns a non-publishing recoverable result without a duplicate version");

const lifecycle={status:"proposed",currentVersion:1,approvedAt:null as string|null,staleAt:null as string|null,history:[] as string[]};assert.equal(mayTransitionSeoAction(lifecycle.status,"approved"),true);lifecycle.status="approved";lifecycle.approvedAt="2026-09-24T09:00:00Z";lifecycle.history.push("approved:v1");lifecycle.staleAt="2026-09-24T10:00:00Z";const approvedRefresh=seoActionRefreshDisposition({status:lifecycle.status,stale_at:lifecycle.staleAt});assert.equal(approvedRefresh.returnStatus,"revision_required");lifecycle.status="researching";lifecycle.history.push("refresh-started:v1");lifecycle.currentVersion++;lifecycle.status="proposed";lifecycle.approvedAt=null;lifecycle.staleAt=null;lifecycle.history.push("proposed:v2");assert.deepEqual(lifecycle.history,["approved:v1","refresh-started:v1","proposed:v2"],"original approval history survives the revised version");assert.equal(lifecycle.approvedAt,null,"the revised proposal does not inherit approval");assert.equal(mayTransitionSeoAction(lifecycle.status,"approved"),true);lifecycle.status="approved";lifecycle.approvedAt="2026-09-24T11:00:00Z";lifecycle.history.push("approved:v2");assert.equal(lifecycle.currentVersion,2);assert.equal(lifecycle.history.at(-1),"approved:v2");

const briefAction={id:"brief",target_page:"https://fixture.invalid/page",query_cluster:["query"],action_type:"meta_description",status:"approved",risk:"low",confidence:.8,expected_benefit:"Relevant snippet",priority_score:50,opportunity_type:"low_ctr",current_metrics:{},previous_metrics:{},competitors_analyzed:0,version_missing:false,approval_blocked:false,refresh_active:false,refresh_expired:false,refresh_failure_category:null,current_version:2,stale_at:null,created_at:"2026-09-24",updated_at:"2026-09-24",proposal:{proposedMetaDescription:"A sufficiently detailed proposed meta description for the fixture page.",explanation:"A sufficiently detailed explanation.",insertionLocation:"Replace meta description",rollbackConcept:"Restore snapshot version one.",currentValue:"The sufficiently detailed current description.",implementationTarget:"HTML head metadata",acceptanceChecks:["Description matches"]}} satisfies SeoAction;assert.equal(implementationBriefEligibility(briefAction),true);assert.match(buildImplementationBrief(briefAction),/Implement this in a separate focused website-update PR/);const unresolvedCannibal={...briefAction,action_type:"cannibalization",opportunity_type:"cannibalization"} as SeoAction;assert.equal(implementationBriefEligibility(unresolvedCannibal),false);assert.throws(()=>buildImplementationBrief(unresolvedCannibal),/Only a current, valid, approved/);
for(const blocked of [{status:"proposed"},{status:"rejected"},{status:"researching"},{status:"revision_required"},{status:"approved",stale_at:"2026-09-24"},{status:"approved",approval_blocked:true},{status:"approved",version_missing:true}]){const candidate={...briefAction,...blocked} as SeoAction;assert.equal(implementationBriefEligibility(candidate),false,JSON.stringify(blocked));assert.throws(()=>buildImplementationBrief(candidate),/Only a current, valid, approved/);}
for(const status of ["proposed","revision_required","rejected"])assert.equal(recoveredRefreshStatus(status,null),status);assert.equal(recoveredRefreshStatus(null,new Date()),"revision_required","stale-approved legacy recovery returns to review");assert.equal(recoveredRefreshStatus(null,null),"proposed");
console.log("SEO actions experience tests passed");
