import assert from "node:assert/strict";
import { isPublicAddress, resolveSafePublicUrl, safeFetchHtml, type PinnedTransport } from "../server/seo/competitorResearch";
const publicA={address:"93.184.216.34",family:4},publicB={address:"142.250.72.14",family:4};
const resolver=(answers:Record<string,Array<{address:string;family:number}>>,calls:string[]=[])=>async(host:string)=>{calls.push(host);return answers[host]??[];};
const transport=(responses:Array<{status?:number;location?:string;remote?:string;body?:string}>):PinnedTransport=>async(url,addresses,options)=>{const item=responses.shift()??{};assert.equal(options.signal.aborted,false);return{status:item.status??200,headers:new Headers({"content-type":"text/html",...(item.location?{location:item.location}:{})}),body:(async function*(){yield new TextEncoder().encode(item.body??"ok")})(),remoteAddress:item.remote??addresses[0].address};};
for(const address of ["127.0.0.1","10.0.0.1","172.16.1.1","192.168.1.1","100.64.0.1","169.254.169.254","0.0.0.0","224.0.0.1","192.0.2.1","::1","fc00::1","fe80::1","2001:db8::1","::ffff:127.0.0.1","::ffff:10.0.0.1"])assert.equal(isPublicAddress(address),false,address);
assert.equal(isPublicAddress(publicA.address),true);
await assert.rejects(()=>resolveSafePublicUrl("https://mixed.test",resolver({"mixed.test":[publicA,{address:"127.0.0.1",family:4}]})),/UNSAFE_URL_ADDRESS/);
for(const rebound of ["127.0.0.1","10.0.0.1","169.254.169.254","fc00::1","::ffff:192.168.1.1"]){let n=0;const changing=async()=>[++n===1?publicA:{address:rebound,family:rebound.includes(":")?6:4}] as any;const calls:string[]=[];const secure: PinnedTransport=async(_url,addresses)=>{calls.push(addresses[0].address);return{status:200,headers:new Headers({"content-type":"text/html"}),body:(async function*(){yield new Uint8Array()})(),remoteAddress:addresses[0].address};};await safeFetchHtml("https://rebind.test",{resolver:changing as any,transport:secure});assert.deepEqual(calls,[publicA.address],"request cannot perform a second uncontrolled lookup");assert.equal(n,1);}
await assert.rejects(()=>safeFetchHtml("https://public.test",{resolver:resolver({"public.test":[publicA],"private.test":[{address:"127.0.0.1",family:4}]}),transport:transport([{status:302,location:"http://private.test/"}])}),/UNSAFE_URL_ADDRESS/);
const calls:string[]=[];const redirected=await safeFetchHtml("https://one.test",{resolver:resolver({"one.test":[publicA],"two.test":[publicB]},calls),transport:transport([{status:302,location:"https://two.test/final"},{body:"done"}])});assert.equal(redirected.html,"done");assert.deepEqual(calls,["one.test","two.test"]);
let observedHost="",observedPin="";await safeFetchHtml("https://tls-name.test/path",{resolver:resolver({"tls-name.test":[publicA]}),transport:async(url,addresses)=>{observedHost=url.hostname;observedPin=addresses[0].address;return transport([{body:"tls"}])(url,addresses,{signal:new AbortController().signal,headers:{}});}});assert.equal(observedHost,"tls-name.test","TLS URL retains original certificate/SNI hostname");assert.equal(observedPin,publicA.address);
await assert.rejects(()=>safeFetchHtml("https://mismatch.test",{resolver:resolver({"mismatch.test":[publicA]}),transport:transport([{remote:publicB.address}])}),/REMOTE_ADDRESS_MISMATCH/);
const aborted=new AbortController();aborted.abort();let sawAbort=false;await assert.rejects(()=>safeFetchHtml("https://abort.test",{resolver:resolver({"abort.test":[publicA]}),signal:aborted.signal,transport:async(_u,_a,{signal})=>{sawAbort=signal.aborted;throw Object.assign(new Error("aborted"),{name:"AbortError"});}}));assert.equal(sawAbort,true);
let timeoutAborted=false;await assert.rejects(()=>safeFetchHtml("https://timeout.test",{resolver:resolver({"timeout.test":[publicA]}),timeoutMs:5,transport:async(_u,_a,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener("abort",()=>{timeoutAborted=true;reject(Object.assign(new Error("timeout"),{name:"AbortError"}));},{once:true}))}));assert.equal(timeoutAborted,true);
for(const raw of ["http://user:pass@example.com","ftp://example.com","http://example.com:8080","http://[::ffff:127.0.0.1]"])await assert.rejects(()=>resolveSafePublicUrl(raw,resolver({} as any)));
console.log("seo-competitor-rebinding.test.ts: all assertions passed");
