/** Fixture render test: actual component markup with mocked API cache; not a full browser integration test. */
import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SeoActionsPanel, buildImplementationBrief, type SeoAction } from "../client/src/components/admin/SeoActionsPanel";
(globalThis as typeof globalThis & {React:typeof React}).React=React;

const action:SeoAction={id:"fixture-action-1",target_page:"https://fixture.invalid/real-estate-crm",query_cluster:["real estate crm for whatsapp leads"],action_type:"meta_description",status:"proposed",risk:"medium",confidence:.7,expected_benefit:"Improve alignment; no uplift is estimated.",priority_score:82,opportunity_type:"low_ctr",current_metrics:{clicks:1,impressions:200,position:8},previous_metrics:{},competitors_analyzed:0,version_missing:false,approval_blocked:false,refresh_active:false,refresh_expired:false,refresh_failure_category:null,current_version:2,stale_at:null,created_at:"2026-09-24T00:00:00Z",updated_at:"2026-09-24T00:00:00Z",proposal:{proposedMetaDescription:"Real Estate CRM for Agents & Teams: Capture WhatsApp property inquiries and assign every lead.",explanation:"Fixture explanation for the recommendation.",insertionLocation:"Replace meta description",rollbackConcept:"Restore fixture snapshot abc123.",observedProblem:"The current description is generic despite visible low-CTR evidence.",currentValue:"A CRM for real estate teams.",rationale:"The replacement uses verified page-specific workflow facts.",evidenceSummary:"Synthetic Search Console metrics and first-party fixture snapshot abc123.",evidenceDateRange:"Synthetic current 28-day fixture",evidenceLimitations:"Synthetic fixture; no competitor research was analyzed.",implementationTarget:"HTML head meta description",repositoryTarget:null,acceptanceChecks:["Deployed description matches the approved value"]},review_history:[{from:"researching",to:"proposed",reason:null,createdAt:"2026-09-24T00:00:00Z"}]};
const key="/api/admin/seo-intelligence/actions?view=review&page=1",client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData([key],{provider:{state:"not_configured"},actions:[action],counts:{review:1,approved:2,history:3},pagination:{page:1,limit:20,total:21,hasMore:true}});
const html=renderToStaticMarkup(<QueryClientProvider client={client}><SeoActionsPanel configured/></QueryClientProvider>);
for(const text of ["Needs review","Approved","History","Search actions by URL or query","Filter by action type","Real Estate CRM for Agents &amp; Teams","Current meta description","Proposed meta description","Copy proposed change","Copy implementation brief","Previous","Next"])assert.match(html,new RegExp(text));
assert.match(html,/sm:grid-cols-\[minmax\(0,1fr\)_minmax\(220px,1fr\)_auto\]/,"desktop row layout is present");assert.match(html,/p-3 sm:p-4/,"narrow layout uses compact padding before desktop breakpoint");assert.match(html,/<details/,"recommendations use native expandable disclosure rows");
const brief=buildImplementationBrief(action);for(const text of [action.id,action.target_page,"A CRM for real estate teams.","HTML head meta description","Unresolved","Rollback reference","approval did not modify website content"])assert.match(brief,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
console.log("SEO Actions fixture SSR/render assertions passed");
