/** Fixture render test: actual component markup with mocked API cache; not a full browser integration test. */
import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SeoActionsPanel, buildImplementationBrief, isSeoActionsQuery, type SeoAction } from "../client/src/components/admin/SeoActionsPanel";
import { readFileSync } from "node:fs";
(globalThis as typeof globalThis & {React:typeof React}).React=React;

const action:SeoAction={id:"fixture-action-1",target_page:"https://fixture.invalid/real-estate-crm",query_cluster:["real estate crm for whatsapp leads"],action_type:"meta_description",status:"approved",risk:"medium",confidence:.7,expected_benefit:"Improve alignment; no uplift is estimated.",priority_score:82,opportunity_type:"low_ctr",current_metrics:{clicks:1,impressions:200,position:8},previous_metrics:{},competitors_analyzed:0,version_missing:false,approval_blocked:false,refresh_active:false,refresh_expired:false,refresh_failure_category:null,current_version:2,stale_at:null,created_at:"2026-09-24T00:00:00Z",updated_at:"2026-09-24T00:00:00Z",proposal:{proposedMetaDescription:"Real Estate CRM for Agents & Teams: Capture WhatsApp property inquiries and assign every lead.",explanation:"Fixture explanation for the recommendation.",insertionLocation:"Replace meta description",rollbackConcept:"Restore fixture snapshot abc123.",observedProblem:"The current description is generic despite visible low-CTR evidence.",currentValue:"A CRM for real estate teams.",rationale:"The replacement uses verified page-specific workflow facts.",evidenceSummary:"Synthetic Search Console metrics and first-party fixture snapshot abc123.",evidenceDateRange:"Synthetic current 28-day fixture",evidenceLimitations:"Synthetic fixture; no competitor research was analyzed.",implementationTarget:"HTML head meta description",repositoryTarget:null,acceptanceChecks:["Deployed description matches the approved value"]},review_history:[{from:"researching",to:"proposed",reason:null,createdAt:"2026-09-24T00:00:00Z"}]};
const cannibal={...action,id:"fixture-cannibal",status:"proposed",action_type:"cannibalization",opportunity_type:"cannibalization",proposal:{...action.proposal,proposedMetaDescription:undefined,contentBrief:"Human ownership review only."},evidence:{materialCurrentPages:[{page:"https://fixture.invalid/primary",current:{clicks:10,impressions:100,position:7},previous:{clicks:8,impressions:90}},{page:"https://fixture.invalid/secondary",current:{clicks:3,impressions:25,position:10},previous:{clicks:2,impressions:20}}],currentVisiblePages:[{page:"https://fixture.invalid/primary",current:{impressions:100}},{page:"https://fixture.invalid/secondary",current:{impressions:25}},{page:"https://fixture.invalid/incidental",current:{impressions:2}}],recommendedPrimaryPage:"https://fixture.invalid/primary",cannibalizationThresholds:{minPageImpressions:50,minPageShare:.1}}} satisfies SeoAction;
const key="/api/admin/seo-intelligence/actions?view=review&page=1",client=new QueryClient({defaultOptions:{queries:{retry:false}}});client.setQueryData([key],{provider:{state:"not_configured"},actions:[action,cannibal],counts:{review:1,approved:2,history:3},pagination:{page:1,limit:20,total:21,hasMore:true}});
const html=renderToStaticMarkup(<QueryClientProvider client={client}><SeoActionsPanel configured/></QueryClientProvider>);
for(const text of ["Needs review","Approved","History","Search actions by URL or query","Filter by action type","Real Estate CRM for Agents &amp; Teams","Current meta description","Proposed meta description","Copy proposed change","Copy implementation brief","Human page-ownership review required","Cannibalization remains review-only until a concrete owner and exact human-approved changes are recorded","Materially competing pages","Incidental diagnostic visibility — not competing","Recommended primary","Previous","Next"])assert.match(html,new RegExp(text));
assert.match(html,/sm:grid-cols-\[minmax\(0,1fr\)_minmax\(220px,1fr\)_auto\]/,"desktop row layout is present");assert.match(html,/p-3 sm:p-4/,"narrow layout uses compact padding before desktop breakpoint");assert.match(html,/<details/,"recommendations use native expandable disclosure rows");
const blockedClient=new QueryClient({defaultOptions:{queries:{retry:false}}}),blocked={...action,id:"blocked-proposed",status:"proposed",approval_blocked:true,invalid_reason:"Legacy proposal"} satisfies SeoAction;blockedClient.setQueryData([key],{provider:{state:"configured"},actions:[blocked],counts:{review:1,approved:0,history:0},pagination:{page:1,limit:20,total:1,hasMore:false}});const blockedHtml=renderToStaticMarkup(<QueryClientProvider client={blockedClient}><SeoActionsPanel configured/></QueryClientProvider>);assert.match(blockedHtml,/Dismiss to History/,"approval-blocked proposed actions retain the authorized rejection path");assert.doesNotMatch(blockedHtml,/Approve — does not publish/,"approval remains blocked");
const brief=buildImplementationBrief(action);for(const text of [action.id,action.target_page,"A CRM for real estate teams.","HTML head meta description","Unresolved","Rollback reference","approval did not modify website content"])assert.match(brief,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
const filteredKeys=["/api/admin/seo-intelligence/actions?view=review&page=2&type=meta_description","/api/admin/seo-intelligence/actions?view=approved&page=1&search=crm","/api/admin/seo-intelligence/actions?view=history&page=4"];for(const filteredKey of filteredKeys)client.setQueryData([filteredKey],{fixture:true});client.setQueryData(["/api/admin/seo-intelligence"],{fixture:true});await client.invalidateQueries({predicate:isSeoActionsQuery,refetchType:"none"});for(const filteredKey of [key,...filteredKeys])assert.equal(client.getQueryState([filteredKey])?.isInvalidated,true,`invalidates ${filteredKey}`);assert.equal(client.getQueryState(["/api/admin/seo-intelligence"])?.isInvalidated,false,"does not invalidate the dashboard query");
const selectedKey=filteredKeys[1],oldKey=filteredKeys[0],selected={actions:[{id:"approved-selected"}]};client.setQueryData([selectedKey],selected);client.setQueryData([oldKey],{actions:[{id:"late-old-view"}]});assert.deepEqual(client.getQueryData([selectedKey]),selected,"a late response remains isolated under its old view/search/filter key");
const panelSource=readFileSync(new URL("../client/src/components/admin/SeoActionsPanel.tsx",import.meta.url),"utf8");assert.doesNotMatch(panelSource,/placeholderData/,"view, search, filter, and pagination changes show loading instead of previous-query rows");assert.match(panelSource,/action\.status==="revision_required"[\s\S]+Dismiss to History/,"revision-required actions have an explicit History exit");
console.log("SEO Actions fixture SSR/render assertions passed");
