import { useState, lazy, Suspense, useLayoutEffect } from "react";
import { Link, useLocation } from "wouter";
import { Helmet } from "react-helmet";
import { useTranslation } from "react-i18next";
import { ArrowRight, CheckCircle2, ChevronRight, Calendar } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
const SiteFooter = lazy(() =>
  import("@/components/SiteFooter").then((m) => ({ default: m.SiteFooter })),
);
const BookDemoModal = lazy(() =>
  import("@/components/BookDemoModal").then((m) => ({ default: m.BookDemoModal })),
);
const LanguageSelector = lazy(() =>
  import("@/components/LanguageSelector").then((m) => ({ default: m.LanguageSelector })),
);
const WelcomeProblemSolution = lazy(() => import("@/pages/welcome/WelcomeProblemSolution"));
const WelcomeBenefitsSection = lazy(() => import("@/pages/welcome/WelcomeBenefitsSection"));
const WelcomeIntegrationsSection = lazy(() => import("@/pages/welcome/WelcomeIntegrationsSection"));
const WelcomeHowPricingBuilt = lazy(() => import("@/pages/welcome/WelcomeHowPricingBuilt"));
const WelcomeTestimonials = lazy(() => import("@/pages/welcome/WelcomeTestimonials"));
const WelcomeFinalCta = lazy(() => import("@/pages/welcome/WelcomeFinalCta"));
import { getDirection } from "@/lib/i18n";
import { MARKETING_URL } from "@/lib/marketingUrl";

/** Public responsive hero (generated by scripts/generate-hero-responsive.mjs). */
const HERO = "/hero/dashboard";
const HERO_AVIF_SRCSET = `${HERO}-400.avif 400w, ${HERO}-640.avif 640w, ${HERO}-768.avif 768w, ${HERO}-1024.avif 1024w`;
const HERO_WEBP_SRCSET = `${HERO}-400.webp 400w, ${HERO}-640.webp 640w, ${HERO}-768.webp 768w, ${HERO}-1024.webp 1024w`;
/** Matches hero px-4 padding; avoids overstating width vs 100vw (helps srcset pick 400–768w on phones). */
const HERO_SIZES = "(max-width: 768px) calc(100vw - 2rem), min(50vw, 704px)";
const HERO_IMG_FALLBACK = `${HERO}-640.webp`;

/** Fixed min-heights reduce layout shift when lazy sections hydrate (approximate final block size). */
function BelowFoldFallback({ className }: { className?: string }) {
  return <div className={className ?? "min-h-[240px] bg-gray-50"} aria-hidden />;
}

export function Welcome() {
  const { user, isLoading: authLoading } = useAuth();
  const [location] = useLocation();
  const { t } = useTranslation();
  const [showDemoModal, setShowDemoModal] = useState(false);
  const isRTL = getDirection() === "rtl";

  const hasStaticShell =
    typeof document !== "undefined" && !!document.getElementById("whachat-static-shell");
  /** index.html paints nav+hero for "/" guests — skip React duplicate until login or non-home route */
  const deferHeroToStaticHtml =
    hasStaticShell && location === "/" && (authLoading || !user);

  useLayoutEffect(() => {
    const shell = document.getElementById("whachat-static-shell");
    if (!shell) return;
    if (location !== "/" || user) {
      document.documentElement.classList.add("wcs-hide-static-marketing");
    } else {
      document.documentElement.classList.remove("wcs-hide-static-marketing");
    }
  }, [location, user]);

  // When Shopify App `application_url` is the app root, installs land as `/?shop=…myshopify.com` — forward to OAuth.
  useLayoutEffect(() => {
    if (typeof window === "undefined" || location !== "/") return;
    const params = new URLSearchParams(window.location.search);
    const shop = params.get("shop");
    if (shop && /^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(shop)) {
      window.location.replace(`/api/shopify/install?shop=${encodeURIComponent(shop)}`);
    }
  }, [location]);

  return (
    <div dir={isRTL ? "rtl" : "ltr"} className={`min-h-screen bg-white overflow-x-hidden ${isRTL ? "text-right" : "text-left"}`}>
      <Helmet>
        <title>WhatsApp & Unified Mailbox | WhachatCRM</title>
        <meta
          name="description"
          content="Manage WhatsApp, Instagram, and SMS in one unified mailbox. The simple CRM for SMBs and Shopify sellers."
        />
        <link rel="canonical" href={`${MARKETING_URL}/`} />
        <meta property="og:title" content="WhatsApp & Unified Mailbox | WhachatCRM" />
        <meta
          property="og:description"
          content="Manage WhatsApp, Instagram, and SMS in one unified mailbox. The simple CRM for SMBs and Shopify sellers."
        />
        <meta property="og:url" content={`${MARKETING_URL}/`} />
        <meta property="og:type" content="website" />
        <meta property="og:image" content={`${MARKETING_URL}/og-image.png`} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content={`${MARKETING_URL}/og-image.png`} />
        <meta name="twitter:title" content="WhatsApp & Unified Mailbox | WhachatCRM" />
        <meta
          name="twitter:description"
          content="Manage WhatsApp, Instagram, and SMS in one unified mailbox. The simple CRM for SMBs and Shopify sellers."
        />
      </Helmet>
      {showDemoModal ? (
        <Suspense fallback={null}>
          <BookDemoModal isOpen={showDemoModal} onClose={() => setShowDemoModal(false)} />
        </Suspense>
      ) : null}
      {!deferHeroToStaticHtml ? (
      <>
      {/* Navigation */}
      <nav className="min-h-[56px] py-3 px-4 md:py-6 md:px-6 flex justify-between items-center max-w-7xl xl:max-w-[1440px] 2xl:max-w-[1536px] mx-auto box-border">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 bg-brand-green rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-lg">W</span>
          </div>
          <span className="font-display font-bold text-xl text-gray-900">WhachatCRM</span>
        </div>
        <div className="flex items-center gap-2 md:gap-4">
          <Link href="/pricing">
            <button className="text-sm font-medium text-gray-600 hover:text-gray-900 hidden sm:block">{t("landing.pricing")}</button>
          </Link>
          <Link href="/blog">
            <button className="text-sm font-medium text-gray-600 hover:text-gray-900 hidden sm:block">{t("landing.blog")}</button>
          </Link>
          <Suspense
            fallback={<div className="h-9 w-9 shrink-0 rounded-md bg-gray-100/90 border border-transparent" aria-hidden />}
          >
            <LanguageSelector variant="compact" className="text-gray-600 hover:text-gray-900 hover:bg-gray-100" />
          </Suspense>
          {user ? (
            <Link href="/app/inbox">
              <button className="text-sm font-medium px-4 py-2 bg-brand-green text-white rounded-full hover:bg-emerald-700">{t("landing.dashboard")}</button>
            </Link>
          ) : (
            <>
              <Link href="/auth?mode=login">
                <button className="text-sm font-medium text-gray-600 hover:text-gray-900 hidden sm:block">{t("landing.login")}</button>
              </Link>
              <Link href="/auth">
                <button className="text-sm font-medium px-4 py-2 bg-brand-green text-white rounded-full hover:bg-emerald-700">{t("landing.startFree")}</button>
              </Link>
            </>
          )}
        </div>
      </nav>

      {/* Hero Section */}
      <section className="px-4 md:px-6 pt-4 md:pt-8 pb-12 md:pb-20 max-w-7xl xl:max-w-[1440px] 2xl:max-w-[1536px] mx-auto">
        {/* Picture first in DOM (earlier fetch); mobile image above fold; md+: headline left via order */}
        <div className="flex flex-col gap-8 md:grid md:grid-cols-2 md:gap-12 xl:gap-16 2xl:gap-20 items-start">
          <div className="relative order-1 w-full md:order-2 animate-hero-image">
            {/*
              Reserve aspect ratio before decode (CLS): intrinsic 704×384.
              Absolute img avoids reflow; object-contain matches prior uncropped look.
            */}
            <div className="relative aspect-[704/384] w-full overflow-hidden rounded-xl border border-gray-200 bg-gray-100 shadow-lg md:rounded-2xl md:shadow-2xl">
              <picture className="absolute inset-0 block">
                <source type="image/avif" srcSet={HERO_AVIF_SRCSET} sizes={HERO_SIZES} />
                <source type="image/webp" srcSet={HERO_WEBP_SRCSET} sizes={HERO_SIZES} />
                <img
                  src={HERO_IMG_FALLBACK}
                  alt="WhachatCRM Dashboard - WhatsApp CRM Interface"
                  className="h-full w-full object-contain object-center md:scale-[1.02] xl:scale-105"
                  width={704}
                  height={384}
                  sizes={HERO_SIZES}
                  loading="eager"
                  fetchPriority="high"
                  decoding="async"
                />
              </picture>
            </div>
          </div>

          <div className="animate-hero-text order-2 md:order-1">
            <h1 className="text-3xl md:text-5xl lg:text-6xl xl:text-7xl font-display font-bold text-gray-900 leading-[1.1] mb-4 md:mb-6">{t("landing.heroTitle")}</h1>
            <p className="text-lg md:text-xl xl:text-2xl text-gray-600 mb-6 md:mb-8 leading-relaxed">{t("landing.heroSubtitle")}</p>

            <div className="flex flex-col gap-3 mb-4">
              <div className="w-full sm:w-auto">
                <Link href={user ? "/app/inbox" : "/auth"}>
                  <button
                    className="w-full sm:w-auto h-14 px-8 bg-brand-green hover:bg-emerald-700 text-white font-semibold rounded-full flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-xl"
                    data-testid="button-hero-cta"
                  >
                    {t("landing.startTrial")}
                    <ArrowRight className="h-5 w-5" />
                  </button>
                </Link>
              </div>
              <div className="w-full sm:w-auto">
                <Link href="/pricing">
                  <button
                    className="w-full sm:w-auto h-12 px-6 bg-white border border-gray-200 text-gray-700 font-medium rounded-full flex items-center justify-center gap-2 hover:bg-gray-50 transition-colors"
                    data-testid="button-hero-pricing"
                  >
                    {t("landing.pricing")}
                    <ChevronRight className="h-4 w-4" />
                  </button>
                </Link>
              </div>
              <div className="flex flex-col items-center sm:items-start">
                <button
                  type="button"
                  onClick={() => setShowDemoModal(true)}
                  className="w-full sm:w-auto h-12 px-6 bg-gradient-to-r from-amber-500 to-orange-500 text-white font-medium rounded-full flex items-center justify-center gap-2 hover:from-amber-600 hover:to-orange-600 transition-colors shadow-md"
                  data-testid="button-book-demo"
                >
                  <Calendar className="h-4 w-4" />
                  {t("landing.bookDemo")}
                </button>
              </div>
            </div>

            <div className="flex items-center gap-2 mb-6">
              <span className="text-sm text-gray-500">{t("landing.noCreditCard")}</span>
            </div>

            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-gray-600">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-brand-green" />
                <span>{t("home.hero.badge1")}</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-brand-green" />
                <span>{t("home.hero.badge2")}</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-brand-green" />
                <span>{t("home.hero.badge3")}</span>
              </div>
            </div>
          </div>
        </div>
      </section>
      </>
      ) : null}

      <Suspense fallback={<BelowFoldFallback className="min-h-[420px] bg-gray-900 [contain-intrinsic-size:auto_420px]" />}>
        <WelcomeProblemSolution />
      </Suspense>

      <Suspense fallback={<BelowFoldFallback className="min-h-[520px] bg-gray-50 [contain-intrinsic-size:auto_520px]" />}>
        <WelcomeBenefitsSection />
      </Suspense>

      <Suspense fallback={<BelowFoldFallback className="min-h-[400px] bg-gradient-to-b from-gray-50 to-white [contain-intrinsic-size:auto_400px]" />}>
        <WelcomeIntegrationsSection />
      </Suspense>

      <Suspense fallback={<BelowFoldFallback className="min-h-[560px] bg-gray-50 [contain-intrinsic-size:auto_560px]" />}>
        <WelcomeHowPricingBuilt />
      </Suspense>

      <Suspense fallback={<BelowFoldFallback className="min-h-[260px] bg-gray-900 [contain-intrinsic-size:auto_260px]" />}>
        <WelcomeTestimonials />
      </Suspense>

      <Suspense fallback={<BelowFoldFallback className="min-h-[320px] bg-gradient-to-br from-brand-green/5 to-brand-teal/5 [contain-intrinsic-size:auto_320px]" />}>
        <WelcomeFinalCta isLoggedIn={!!user} />
      </Suspense>

      <Suspense fallback={<footer className="min-h-[240px] bg-gray-50 border-t border-gray-100 [contain-intrinsic-size:auto_240px]" aria-hidden />}>
        <SiteFooter />
      </Suspense>
    </div>
  );
}
