import type { Express } from "express";
import { ObjectStorageService, ObjectNotFoundError } from "./objectStorage";

/**
 * Object Storage Routes
 * =====================
 *
 * Public surface (no auth required):
 *   GET /objects/uploads/:filename
 *     Serves outbound media files uploaded via POST /api/media/upload.
 *     Only the `uploads/` sub-prefix is publicly reachable — everything else
 *     in the bucket is blocked by the catch-all below.
 *
 * Authenticated surface:
 *   POST /api/uploads/request-url
 *     Returns a presigned GCS URL so the client can upload directly to GCS.
 *
 * Blocked surface:
 *   GET /objects/* (anything not matching /objects/uploads/:filename)
 *     Returns 403 — no other bucket paths are exposed publicly.
 *
 * Security notes
 * --------------
 * - Only files under the `uploads/` sub-prefix are public.  No other paths
 *   inside PRIVATE_OBJECT_DIR can be reached via HTTP.
 * - Filenames are validated against a strict allowlist regex before the GCS
 *   lookup is attempted, blocking path traversal and non-media extensions.
 * - X-Content-Type-Options: nosniff prevents MIME-type sniffing in browsers.
 * - X-Frame-Options: DENY prevents the file from being embedded in an iframe.
 * - PDFs and audio files get Content-Disposition: attachment so browsers
 *   download them rather than render/execute them inline.
 * - All blocked attempts (wrong prefix, bad filename) are logged for monitoring.
 * - The bucket name and object path are never included in error responses.
 */

/**
 * Allowlist for filenames generated by POST /api/media/upload.
 * Pattern: <unix-ms>-<random-9-digit>.<allowed-ext>
 * Allows letters, digits, underscores, and hyphens in the stem; only the
 * extensions we actually produce.  No slashes, dots in stem, or traversal
 * sequences are possible.
 */
const UPLOAD_FILENAME_RE =
  /^[\w][\w\-]*\.(jpg|jpeg|png|webp|pdf|mp3|m4a|ogg|mp4)$/i;

/**
 * MIME types that should be forced to download rather than rendered inline.
 * Images are excluded — browsers handle them safely inline and the chat UI
 * depends on inline rendering for the image preview bubble.
 * PDFs, audio, and video are forced to download to avoid inline execution risks.
 */
const FORCE_DOWNLOAD_MIME_PREFIXES = ["application/pdf", "audio/", "video/"];

export function registerObjectStorageRoutes(app: Express): void {
  const objectStorageService = new ObjectStorageService();

  // -------------------------------------------------------------------------
  // POST /api/uploads/request-url
  // Authenticated — returns a presigned GCS URL for direct-to-GCS uploads.
  // -------------------------------------------------------------------------
  app.post("/api/uploads/request-url", async (req: any, res) => {
    try {
      if (!req.user) {
        return res.status(401).json({ error: "Unauthorized" });
      }

      const { name, size, contentType } = req.body;

      if (!name) {
        return res.status(400).json({ error: "Missing required field: name" });
      }

      if (size && size > 25 * 1024 * 1024) {
        return res.status(400).json({ error: "File too large. Max 25MB." });
      }

      const uploadURL = await objectStorageService.getObjectEntityUploadURL();
      const objectPath = objectStorageService.normalizeObjectEntityPath(uploadURL);

      res.json({
        uploadURL,
        objectPath,
        metadata: { name, size, contentType },
      });
    } catch (error) {
      console.error("[ObjectServe] Error generating upload URL:", error);
      res.status(500).json({ error: "Failed to generate upload URL" });
    }
  });

  // -------------------------------------------------------------------------
  // GET /objects/uploads/:filename
  //
  // The ONLY publicly accessible object path.  Serves media files created by
  // POST /api/media/upload (images, PDFs, audio, video).
  //
  // Security checks (in order):
  //   1. Filename regex allowlist — rejects traversal, unknown extensions,
  //      embedded slashes, or anything that doesn't match our generated names
  //   2. Double-check: reject if the decoded filename still contains `/` or `..`
  //   3. GCS lookup — ObjectNotFoundError → 404
  //   4. Security headers on every successful response
  // -------------------------------------------------------------------------
  app.get("/objects/uploads/:filename", async (req: any, res) => {
    const raw = req.params.filename as string;

    // Guard 1 — allowlist check
    if (!UPLOAD_FILENAME_RE.test(raw)) {
      console.warn(
        `[ObjectServe] Rejected filename outside allowlist: "${raw}" from ${req.ip}`
      );
      return res.status(400).json({ error: "Invalid filename" });
    }

    // Guard 2 — defense in depth: reject any decoded traversal sequences
    if (raw.includes("..") || raw.includes("/") || raw.includes("\\")) {
      console.warn(
        `[ObjectServe] Rejected traversal attempt in filename: "${raw}" from ${req.ip}`
      );
      return res.status(400).json({ error: "Invalid filename" });
    }

    const objectPath = `/objects/uploads/${raw}`;

    try {
      const objectFile =
        await objectStorageService.getObjectEntityFile(objectPath);

      // Fetch metadata for accurate Content-Type (stored at upload time)
      const [metadata] = await objectFile.getMetadata();
      const contentType =
        (metadata.contentType as string | undefined) || "application/octet-stream";

      // Security headers
      res.set("X-Content-Type-Options", "nosniff");
      res.set("X-Frame-Options", "DENY");
      res.set("Content-Type", contentType);
      res.set("Cache-Control", "public, max-age=31536000, immutable");

      // Force download for types browsers might execute or render dangerously
      if (FORCE_DOWNLOAD_MIME_PREFIXES.some((p) => contentType.startsWith(p))) {
        res.set(
          "Content-Disposition",
          `attachment; filename="${encodeURIComponent(raw)}"`
        );
      }

      if (metadata.size) {
        res.set("Content-Length", String(metadata.size));
      }

      console.log(
        `[ObjectServe] Serving upload — file="${raw}" type=${contentType} ip=${req.ip}`
      );

      const stream = objectFile.createReadStream();
      stream.on("error", (err: Error) => {
        console.error(`[ObjectServe] Stream error for "${raw}": ${err.message}`);
        if (!res.headersSent) {
          res.status(500).json({ error: "Error streaming file" });
        }
      });
      stream.pipe(res);
    } catch (error: any) {
      if (error instanceof ObjectNotFoundError) {
        return res.status(404).json({ error: "Not found" });
      }
      console.error(
        `[ObjectServe] Unexpected error for "${raw}": ${error.message}`
      );
      return res.status(500).json({ error: "Failed to serve file" });
    }
  });

  // -------------------------------------------------------------------------
  // GET /objects/* — catch-all
  //
  // Any /objects/ path that does NOT match /objects/uploads/:filename is
  // blocked.  This prevents accidental public exposure of other bucket paths
  // (exports, logs, private data, etc.).
  //
  // Returns 403 (not 404) so that if a misconfigured caller sends a wrong
  // path, the error is clearly "forbidden" rather than "not found", which
  // aids debugging without revealing what does or doesn't exist.
  // -------------------------------------------------------------------------
  app.get("/objects/*", (req: any, res) => {
    console.warn(
      `[ObjectServe] Blocked access to non-upload path: "${req.path}" from ${req.ip}`
    );
    return res.status(403).json({ error: "Forbidden" });
  });
}
