import { useRef } from "react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { ProspectVariablePicker } from "./ProspectVariablePicker";
import { ProspectAiPlaceholderPicker } from "./ProspectAiPlaceholderPicker";

type Props = {
  subject: string;
  body: string;
  onSubjectChange: (value: string) => void;
  onBodyChange: (value: string) => void;
  showAiPlaceholders?: boolean;
};

function insertAtCursor(
  el: HTMLInputElement | HTMLTextAreaElement | null,
  current: string,
  token: string,
  onChange: (next: string) => void,
) {
  if (!el) {
    onChange(current + token);
    return;
  }
  const start = el.selectionStart ?? current.length;
  const end = el.selectionEnd ?? current.length;
  const next = current.slice(0, start) + token + current.slice(end);
  onChange(next);
  requestAnimationFrame(() => {
    const pos = start + token.length;
    el.focus();
    el.setSelectionRange(pos, pos);
  });
}

export function ProspectTemplateEditor({
  subject,
  body,
  onSubjectChange,
  onBodyChange,
  showAiPlaceholders = false,
}: Props) {
  const subjectRef = useRef<HTMLInputElement>(null);
  const bodyRef = useRef<HTMLTextAreaElement>(null);
  const lastFocus = useRef<"subject" | "body">("body");

  const insertToken = (token: string) => {
    if (lastFocus.current === "subject") {
      insertAtCursor(subjectRef.current, subject, token, onSubjectChange);
    } else {
      insertAtCursor(bodyRef.current, body, token, onBodyChange);
    }
  };

  return (
    <div className="space-y-3" data-testid="pi-template-editor">
      <div className="flex flex-wrap items-center gap-2">
        <ProspectVariablePicker onInsert={insertToken} />
        {showAiPlaceholders ? <ProspectAiPlaceholderPicker onInsert={insertToken} /> : null}
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="pi-template-subject">Subject</Label>
        <Input
          id="pi-template-subject"
          ref={subjectRef}
          value={subject}
          onFocus={() => {
            lastFocus.current = "subject";
          }}
          onChange={(e) => onSubjectChange(e.target.value)}
          placeholder="Quick idea for {{business_name}}"
          data-testid="pi-template-subject"
        />
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="pi-template-body">Message</Label>
        <Textarea
          id="pi-template-body"
          ref={bodyRef}
          rows={10}
          value={body}
          onFocus={() => {
            lastFocus.current = "body";
          }}
          onChange={(e) => onBodyChange(e.target.value)}
          placeholder={
            showAiPlaceholders
              ? "Hi {{first_name}},\n\n{{ai_opening}}\n\n{{ai_reason}}\n\n{{ai_cta}}\n\nBest,"
              : "Hi {{first_name}},\n\nI help {{business_name}} teams in {{city}}…\n\nBest,"
          }
          className="min-h-[200px] font-mono text-[13px]"
          data-testid="pi-template-body"
        />
        <p className="text-[11px] text-gray-500">
          {showAiPlaceholders
            ? "Only {{ai_…}} placeholders are generated by AI. Everything else stays exactly as written."
            : "AI will not rewrite this template. Only variables you insert are replaced."}
        </p>
      </div>
    </div>
  );
}
