import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Check, ChevronDown, Clipboard, Loader2, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const TOKEN_KEY="whachat_admin_token";
const request=async(url:string,init?:RequestInit)=>{const token=localStorage.getItem(TOKEN_KEY),response=await fetch(url,{...init,credentials:"include",headers:{...(token?{"x-admin-token":token}:{}),...init?.headers}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;};
type PageEvidence={page:string;urls?:string[];current?:Record<string,number>;previous?:Record<string,number>};
export type SeoAction={id:string;target_page:string;query_cluster:string[];action_type:string;status:string;risk:string;confidence:number;expected_benefit:string;priority_score:number;opportunity_type:string;current_metrics:Record<string,number>;previous_metrics:Record<string,number>;competitors_analyzed:number;version_missing:boolean;approval_blocked:boolean;invalid_reason?:string|null;refresh_active:boolean;refresh_expired:boolean;refresh_failure_category:string|null;current_version:number;stale_at:string|null;created_at:string;updated_at:string;evidence?:{competingPages?:PageEvidence[];materialCurrentPages?:PageEvidence[];currentVisiblePages?:PageEvidence[];recommendedPrimaryPage?:string|null;cannibalizationThresholds?:{minPageImpressions?:number;minPageShare?:number}};proposal:null|{proposedTitle?:string;proposedMetaDescription?:string;proposedContent?:string;contentBrief?:string;explanation:string;insertionLocation:string;rollbackConcept:string;observedProblem?:string;currentValue?:string;rationale?:string;evidenceSummary?:string;evidenceDateRange?:string;evidenceLimitations?:string;implementationTarget?:string;repositoryTarget?:string|null;acceptanceChecks?:string[]};review_history?:Array<{from:string|null;to:string;reason:string|null;createdAt:string}>;prior_versions?:Array<{version:number;createdAt:string}>};
type View="review"|"approved"|"history";type Response={provider:{state:string};actions:SeoAction[];counts:Record<View,number>;pagination:{page:number;limit:number;total:number;hasMore:boolean}};
export const isSeoActionsQuery=(query:{queryKey:readonly unknown[]})=>String(query.queryKey[0]).startsWith("/api/admin/seo-intelligence/actions");
export const actionLifecycleLabel=(action:Pick<SeoAction,"status"|"approval_blocked">)=>action.approval_blocked||action.status==="revision_required"?"Outdated — refresh required":action.status==="proposed"?"Ready for review":action.status==="approved"?"Approved, not applied":["executing","measuring"].includes(action.status)?"Awaiting implementation":action.status==="kept"?"Verified as applied":action.status.replaceAll("_"," ");
export function implementationBriefEligibility(action:SeoAction){const p=action.proposal,hasChange=Boolean(p?.proposedMetaDescription||p?.proposedTitle||p?.proposedContent||p?.contentBrief),valid=Boolean(p?.currentValue&&p?.implementationTarget&&p?.rollbackConcept&&p?.acceptanceChecks?.length&&hasChange);return action.action_type!=="cannibalization"&&action.status==="approved"&&!action.stale_at&&!action.approval_blocked&&!action.version_missing&&valid;}
export function buildImplementationBrief(action:SeoAction){if(!implementationBriefEligibility(action))throw new Error("Only a current, valid, approved SEO action can produce an implementation brief");const p=action.proposal!,proposed=p.proposedMetaDescription||p.proposedTitle||p.proposedContent||p.contentBrief!;return [`SEO implementation brief — action ${action.id} v${action.current_version}`,`URL: ${action.target_page}`,"Status: Approved, not applied",`Current value: ${p.currentValue}`,`Proposed value: ${proposed}`,`Target location: ${p.implementationTarget}`,`Repository editing target: ${p.repositoryTarget||"Unresolved — locate the URL's source before editing"}`,"Acceptance checks:",...p.acceptanceChecks!.map(check=>`- ${check}`),`Rollback reference: ${p.rollbackConcept}`,"Publication: approval did not modify website content. Implement this in a separate focused website-update PR."].join("\n");}
const proposedValue=(action:SeoAction)=>action.proposal?.proposedMetaDescription||action.proposal?.proposedTitle||action.proposal?.proposedContent||action.proposal?.contentBrief||"Proposal unavailable";
export function SeoActionsPanel({configured}:{configured:boolean}){const client=useQueryClient(),[view,setView]=useState<View>("review"),[search,setSearch]=useState(""),[type,setType]=useState(""),[page,setPage]=useState(1),[copied,setCopied]=useState<string|null>(null),params=new URLSearchParams({view,page:String(page),...(search?{search}:{}),...(type?{type}:{})}),key=`/api/admin/seo-intelligence/actions?${params}`;
 const actions=useQuery<Response>({queryKey:[key],queryFn:()=>request(key),placeholderData:previous=>previous});
 const refresh=()=>client.invalidateQueries({predicate:isSeoActionsQuery});
 const analyze=useMutation({mutationFn:()=>request("/api/admin/seo-intelligence/actions/analyze",{method:"POST"}),onSuccess:refresh});
 const decide=useMutation({mutationFn:({id,decision,reason}:{id:string;decision:string;reason?:string})=>request(`/api/admin/seo-intelligence/actions/${id}/${decision}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason})}),onSuccess:refresh});
 const changeView=(next:View)=>{setView(next);setPage(1);};const copy=async(action:SeoAction,brief=false)=>{await navigator.clipboard.writeText(brief?buildImplementationBrief(action):proposedValue(action));setCopied(`${action.id}:${brief?"brief":"change"}`);setTimeout(()=>setCopied(null),1500);};
 return <section className="bg-white border rounded-xl p-4 space-y-4" data-testid="seo-actions">
  <div className="flex flex-col sm:flex-row gap-3 justify-between"><div><h3 className="font-semibold flex items-center gap-2"><ShieldCheck className="h-4 w-4"/>SEO Actions</h3><p className="text-xs text-gray-500 max-w-2xl">Approval records a decision only. It does not publish. Copy the implementation brief into Codex to create a separate, focused website-update PR; deployment and verification happen afterward.</p></div><div className="flex gap-2"><Button variant="outline" aria-label="Refresh SEO actions" onClick={()=>actions.refetch()} disabled={actions.isFetching}><RefreshCw className={`h-4 w-4 ${actions.isFetching?"animate-spin":""}`}/></Button><Button onClick={()=>analyze.mutate()} disabled={analyze.isPending||!configured}><Search className="h-4 w-4 mr-2"/>{analyze.isPending?"Analyzing…":"Analyze opportunities"}</Button></div></div>
  <div className="flex gap-1 border-b overflow-x-auto" role="tablist">{(["review","approved","history"] as View[]).map(tab=><button key={tab} role="tab" aria-selected={view===tab} onClick={()=>changeView(tab)} className={`px-3 py-2 text-sm whitespace-nowrap border-b-2 ${view===tab?"border-blue-600 text-blue-700":"border-transparent text-gray-500"}`}>{tab==="review"?"Needs review":tab[0].toUpperCase()+tab.slice(1)} <span className="ml-1 rounded-full bg-gray-100 px-2 py-0.5">{actions.data?.counts[tab]??"—"}</span></button>)}</div>
  <div className="grid sm:grid-cols-[1fr_220px] gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input aria-label="Search actions by URL or query" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search URL or query" className="w-full border rounded-md py-2 pl-9 pr-3 text-sm"/></label><select aria-label="Filter by action type" value={type} onChange={e=>{setType(e.target.value);setPage(1);}} className="border rounded-md px-3 py-2 text-sm"><option value="">All action types</option><option value="meta_description">Meta descriptions</option><option value="content_expansion">Content expansion</option><option value="cannibalization">Cannibalization review</option></select></div>
  {actions.data?.provider.state==="not_configured"&&<div className="bg-amber-50 border border-amber-200 rounded p-2 text-xs text-amber-900">Competitor research is not configured. Recommendations explicitly identify this limitation and rely on first-party snapshots plus Search Console evidence.</div>}
  {actions.isLoading&&<div className="py-8 text-center text-sm text-gray-500"><Loader2 className="inline h-4 w-4 animate-spin mr-2"/>Loading the full review queue…</div>}
  {actions.isError&&<div className="border border-red-200 bg-red-50 rounded p-4 text-sm text-red-800"><AlertCircle className="inline h-4 w-4 mr-2"/>{actions.error.message}<Button variant="outline" size="sm" className="ml-3" onClick={()=>actions.refetch()}>Try again</Button></div>}
  {!actions.isLoading&&!actions.isError&&actions.data?.actions.length===0&&<div className="py-8 text-center"><p className="font-medium">No {view==="review"?"actions need review":`${view} actions match`}.</p><p className="text-sm text-gray-500 mt-1">{search||type?"Clear the search or filter to see other actions.":view==="review"?"Run analysis after Search Console synchronization to look for supported opportunities.":"Decisions remain here as an audit history."}</p></div>}
  <div className="space-y-2">{actions.data?.actions.map(action=><details key={action.id} className="group border rounded-lg overflow-hidden"><summary className="list-none cursor-pointer p-3 hover:bg-gray-50"><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(220px,1fr)_auto] items-center"><div className="min-w-0"><p className="text-sm font-medium truncate">{action.target_page}</p><p className="text-xs text-gray-500 truncate"><span className="sr-only">Search Console query: </span>{action.query_cluster.join(", ")}</p></div><p className="text-sm line-clamp-2">{proposedValue(action)}</p><div className="flex items-center gap-2 sm:justify-end"><Badge variant={action.approval_blocked?"destructive":"secondary"}>{actionLifecycleLabel(action)}</Badge><span className="text-xs whitespace-nowrap">P{Math.round(Number(action.priority_score))}</span><ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180"/></div></div></summary><div className="border-t p-3 sm:p-4 space-y-4 text-sm">
   {action.approval_blocked&&<div className="bg-amber-50 border border-amber-200 rounded p-3"><strong>This proposal is outdated or invalid under current rules.</strong> {action.invalid_reason&&<span>{action.invalid_reason}. </span>}It cannot be approved. Refresh re-evaluates it while preserving this action ID, earlier versions, and review history.</div>}
   <div><h4 className="font-semibold">Observed problem</h4><p>{action.proposal?.observedProblem||action.proposal?.explanation||"The stored version predates the current evidence format; refresh is required."}</p></div>
   <div className="grid md:grid-cols-2 gap-3"><div className="bg-gray-50 rounded p-3 min-w-0"><strong>Current {action.action_type==="meta_description"?"meta description":"page section"}</strong><p className="mt-1 whitespace-pre-wrap break-words">{action.proposal?.currentValue||"Unavailable in this older proposal"}</p></div><div className="bg-blue-50 rounded p-3 min-w-0"><strong>{action.action_type==="meta_description"?"Proposed meta description":"Exact proposed change"}</strong><p className="mt-1 whitespace-pre-wrap break-words">{proposedValue(action)}</p><p className="text-xs mt-2"><strong>Target:</strong> {action.proposal?.implementationTarget||action.proposal?.insertionLocation||"Unresolved"}</p></div></div>
   <div><h4 className="font-semibold">Why this addresses the problem</h4><p>{action.proposal?.rationale||"Refresh this older proposal for a current rationale."}</p></div>
   <div className="bg-slate-50 rounded p-3 space-y-1"><strong>Evidence and limitations</strong><p>{action.proposal?.evidenceSummary||JSON.stringify(action.current_metrics)}</p><p>{action.proposal?.evidenceDateRange}</p><p className="text-xs text-gray-600">{action.proposal?.evidenceLimitations||`Competitors analyzed: ${action.competitors_analyzed}. No causal uplift is claimed.`}</p></div>
   {action.opportunity_type==="cannibalization"&&<div className="bg-amber-50 border border-amber-200 rounded p-3 space-y-2"><strong>Human page-ownership review required</strong><p className="text-xs">These are evidence only. Do not automatically redirect, canonicalize, delete, merge, or consolidate a page.</p><div><strong className="text-xs">Materially competing pages</strong>{(action.evidence?.materialCurrentPages||action.evidence?.competingPages||[]).map(page=><p key={page.page} className="text-xs mt-1 break-all">{page.page} · current {page.current?.clicks??"—"} clicks / {page.current?.impressions??"—"} impressions / position {page.current?.position??"—"} · previous {page.previous?.clicks??"—"} clicks / {page.previous?.impressions??"—"} impressions</p>)}</div><p className="text-xs"><strong>Recommended primary:</strong> {action.evidence?.recommendedPrimaryPage||"Ambiguous — human decision required"}</p><p className="text-xs">Materiality rule: at least {action.evidence?.cannibalizationThresholds?.minPageImpressions??"configured"} impressions or {action.evidence?.cannibalizationThresholds?.minPageShare!=null?`${Math.round(action.evidence.cannibalizationThresholds.minPageShare*100)}%`:"configured share"} of cluster impressions.</p>{(()=>{const material=new Set((action.evidence?.materialCurrentPages||action.evidence?.competingPages||[]).map(page=>page.page)),incidental=(action.evidence?.currentVisiblePages||[]).filter(page=>!material.has(page.page));return incidental.length?<div><strong className="text-xs">Incidental diagnostic visibility — not competing</strong>{incidental.map(page=><p key={page.page} className="text-xs mt-1 break-all">{page.page} · {page.current?.impressions??"—"} current impressions</p>)}</div>:null;})()}</div>}
   <div className="border rounded p-3"><strong>{implementationBriefEligibility(action)?"Implementation handoff":"Read-only proposal preview"}</strong><p className="text-xs mt-1">{implementationBriefEligibility(action)?`Repository target: ${action.proposal?.repositoryTarget||"Unresolved — Codex must locate the source for this URL before editing."}`:action.action_type==="cannibalization"?"Cannibalization remains review-only until a concrete owner and exact human-approved changes are recorded; this action cannot create implementation instructions.":`${actionLifecycleLabel(action)}. Approve a current, valid proposal before creating implementation instructions.`}</p><p className="text-xs">Rollback: {action.proposal?.rollbackConcept||"Use the linked first-party snapshot."}</p><div className="flex flex-wrap gap-2 mt-3"><Button size="sm" variant="outline" onClick={()=>copy(action)}><Clipboard className="h-4 w-4 mr-1"/>{copied===`${action.id}:change`?<><Check className="h-4 w-4 mr-1"/>Copied</>:"Copy proposed change"}</Button>{implementationBriefEligibility(action)&&<Button size="sm" variant="outline" onClick={()=>copy(action,true)}><Clipboard className="h-4 w-4 mr-1"/>Copy implementation brief</Button>}</div></div>
   <div className="flex flex-wrap gap-2">{action.status==="proposed"&&!action.approval_blocked&&!action.version_missing&&<><Button size="sm" onClick={()=>decide.mutate({id:action.id,decision:"approve"})}>Approve — does not publish</Button><Button size="sm" variant="outline" onClick={()=>decide.mutate({id:action.id,decision:"reject",reason:"Rejected in admin review"})}>Reject</Button></>} {(["proposed","revision_required","rejected"].includes(action.status)||(action.status==="approved"&&action.approval_blocked)||action.refresh_expired)&&!action.version_missing&&<Button size="sm" variant="ghost" disabled={action.refresh_active} onClick={()=>decide.mutate({id:action.id,decision:"regenerate"})}><RefreshCw className="h-4 w-4 mr-1"/>Re-evaluate with current rules</Button>}</div>
   {!!action.review_history?.length&&<details><summary className="cursor-pointer text-xs text-gray-600">Review history ({action.review_history.length})</summary><ul className="mt-2 text-xs space-y-1">{action.review_history.map((event,index)=><li key={index}>{new Date(event.createdAt).toLocaleString()}: {event.from||"created"} → {event.to}{event.reason?` — ${event.reason}`:""}</li>)}</ul></details>}
  </div></details>)}</div>
  {!!actions.data?.pagination.total&&<div className="flex items-center justify-between text-sm"><span>Showing {(page-1)*actions.data.pagination.limit+1}–{Math.min(page*actions.data.pagination.limit,actions.data.pagination.total)} of {actions.data.pagination.total}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</Button><Button size="sm" variant="outline" disabled={!actions.data.pagination.hasMore} onClick={()=>setPage(value=>value+1)}>Next</Button></div></div>}
  {(analyze.isError||decide.isError)&&<p className="text-sm text-red-700">{(analyze.error||decide.error)?.message}</p>}
 </section>;
}
