/** Public admin feedback never includes provider errors, credentials, or SQL. */
const messages: Record<string, string> = {
  REFRESH_DATA_UNAVAILABLE: "Search Console history is incomplete. Sync the full comparison period before refreshing this draft.",
  NO_MATERIAL_IMPROVEMENT: "The new draft did not pass the quality checks. The previous proposal was preserved.",
  PAGE_FETCH_FAILED: "The page could not be captured. The previous proposal was preserved.",
  PAGE_SNAPSHOT_PERSIST_FAILED: "Page evidence could not be saved. The previous proposal was preserved.",
  REFRESH_IDENTITY_CONFLICT: "A proposal for the same page and query is already active. Review that proposal instead.",
  QUERY_LANGUAGE_MISMATCH: "The query language does not match the target page. The previous proposal was preserved.",
  QUERY_LANGUAGE_UNCERTAIN: "The query language needs review. The previous proposal was preserved.",
  INSUFFICIENT_INTEGRATION_EVIDENCE: "The page does not support the requested integration claims. The previous proposal was preserved.",
  REFRESH_FAILED: "Draft refresh failed. The previous proposal was preserved.",
};

export function seoRefreshMessage(category: string) {
  return messages[category] ?? messages.REFRESH_FAILED;
}

export function seoRefreshReasonMessage(reason: string) {
  if (reason.startsWith("unsupported_fact:")) return "The draft included a feature or price not supported by this page.";
  return ({
    insufficient_evidence: "The captured page has too little evidence for a draft.",
    ai_provider_failure_or_malformed_json: "The AI provider did not return a valid draft.",
    ai_provider_failure: "The AI provider did not return a valid draft.",
    inappropriate_length: "The draft length was outside the allowed range.",
    generic_or_weak: "The draft was too generic.",
    unsupported_claim: "The draft included an unsupported claim.",
    query_intent_not_covered: "The draft did not answer the target query.",
    keyword_stuffing: "The draft repeated query terms too often.",
    duplicates_existing_content: "The draft copied content already on the page.",
    insufficient_first_party_grounding: "The draft was not sufficiently grounded in page facts.",
    missing_review_context: "The draft was missing its placement or explanation.",
  } as Record<string, string>)[reason] ?? "A draft quality check did not pass.";
}

export function safeSeoRefreshFailure(error: unknown) {
  const value = error as { category?: unknown; audit?: { reviewerScores?: Array<{ rejectionReasons?: unknown }> } } | null;
  const category = typeof value?.category === "string" && Object.prototype.hasOwnProperty.call(messages, value.category) ? value.category : "REFRESH_FAILED";
  // Only reviewer identifiers generated by our code are safe to expose.
  const reasons = [...new Set((value?.audit?.reviewerScores ?? []).flatMap(score =>
    Array.isArray(score.rejectionReasons) ? score.rejectionReasons.filter((reason): reason is string =>
      typeof reason === "string" && /^[a-z_]+(?::[a-z ]+)?$/.test(reason) && reason.length <= 80) : []
  ))].slice(0, 12);
  return { category, message: seoRefreshMessage(category), reasons };
}
