/** Public admin feedback never includes provider errors, credentials, or SQL. */
const messages: Record<string, string> = {
  REFRESH_DATA_UNAVAILABLE: "Search Console history is incomplete. Sync the full comparison period before refreshing this draft.",
  NO_MATERIAL_IMPROVEMENT: "The new draft did not pass the quality checks. The previous proposal was preserved.",
  PAGE_FETCH_FAILED: "The page could not be captured. The previous proposal was preserved.",
  PAGE_SNAPSHOT_PERSIST_FAILED: "Page evidence could not be saved. The previous proposal was preserved.",
  REFRESH_IDENTITY_CONFLICT: "A proposal for the same page and query is already active. Review that proposal instead.",
  QUERY_LANGUAGE_MISMATCH: "The query language does not match the target page. The previous proposal was preserved.",
  QUERY_LANGUAGE_UNCERTAIN: "The query language needs review. The previous proposal was preserved.",
  INSUFFICIENT_INTEGRATION_EVIDENCE: "The page does not support the requested integration claims. The previous proposal was preserved.",
  REFRESH_FAILED: "Draft refresh failed. The previous proposal was preserved.",
};

export function seoRefreshMessage(category: string) {
  return messages[category] ?? messages.REFRESH_FAILED;
}

export function safeSeoRefreshFailure(error: unknown) {
  const value = error as { category?: unknown; audit?: { reviewerScores?: Array<{ rejectionReasons?: unknown }> } } | null;
  const category = typeof value?.category === "string" && Object.prototype.hasOwnProperty.call(messages, value.category) ? value.category : "REFRESH_FAILED";
  // Only reviewer identifiers generated by our code are safe to expose.
  const reasons = [...new Set((value?.audit?.reviewerScores ?? []).flatMap(score =>
    Array.isArray(score.rejectionReasons) ? score.rejectionReasons.filter((reason): reason is string =>
      typeof reason === "string" && /^[a-z_]+(?::[a-z ]+)?$/.test(reason) && reason.length <= 80) : []
  ))].slice(0, 12);
  return { category, message: seoRefreshMessage(category), reasons };
}
