/** Local synthetic examples only. This script never fetches pages or writes a database. */
import { buildProposal, InsufficientSeoEvidenceError } from "../server/seo/actionService";
import { clusterAndScoreOpportunities } from "../server/seo/opportunityPlanner";
import type { SeoMetricRow } from "../server/seo/opportunities";

type Fixture={path:string;metrics:SeoMetricRow[];snapshot:{fingerprint:string;title:string;metaDescription:string;headings:string[];sections:string[];competitorCount:number};before:string};
const fixtures:Fixture[]=[
 {path:"/real-estate-crm",metrics:[{query:"real estate crm for whatsapp leads",page:"https://whachatcrm.com/real-estate-crm",clicks:1,impressions:200,position:8}],snapshot:{fingerprint:"1".repeat(64),title:"Real Estate CRM for Agents & Teams | WhachatCRM",metaDescription:"A CRM for real estate teams.",headings:["Real Estate CRM That Meets Buyers Where They Message"],sections:["Capture WhatsApp property inquiries, assign each lead to an agent, and keep qualification notes and follow-up in one shared inbox."],competitorCount:0},before:"Explore WhachatCRM for real estate crm for whatsapp leads: organize conversations, follow up consistently, and manage customer relationships in one workspace."},
 {path:"/best-whatsapp-crm-2026",metrics:[{query:"best whatsapp crm with ai automation and omnichannel team inbox in 2026",page:"https://whachatcrm.com/best-whatsapp-crm-2026",clicks:8,impressions:113,position:8},{query:"best whatsapp crm with ai automation and omnichannel team inbox in 2026",page:"https://whachatcrm.com/",clicks:0,impressions:2,position:30}],snapshot:{fingerprint:"2".repeat(64),title:"Best WhatsApp CRM in 2026 | Omnichannel CRM Comparison",metaDescription:"Compare the best WhatsApp CRM platforms in 2026.",headings:["Best WhatsApp CRM in 2026","What to compare"],sections:["The best WhatsApp CRM in 2026 depends on channel and team needs. Compare official API access, an omnichannel team inbox, AI assistance, automation, integrations, and transparent Meta pricing."],competitorCount:0},before:"Expand the existing page with an original section that directly answers the target query, covering workflow, fit, and next steps."},
 {path:"/zoko-alternative",metrics:[{query:"zoko alternative",page:"https://whachatcrm.com/zoko-alternative",clicks:40,impressions:959,position:8},{query:"zoko alternative",page:"https://whachatcrm.com/",clicks:0,impressions:3,position:30}],snapshot:{fingerprint:"3".repeat(64),title:"Zoko Alternative 2026: Shopify WhatsApp vs Omnichannel CRM | WhachatCRM",metaDescription:"Compare Zoko with an omnichannel CRM for Shopify and WhatsApp teams.",headings:["Zoko Alternative","Shopify plus omnichannel — not Shopify only"],sections:["Teams evaluating a Zoko alternative can compare Shopify order context, WhatsApp workflows, Email, social channels, web chat, shared inbox collaboration, and CRM follow-up."],competitorCount:0},before:"Expand the existing page with an original section that directly answers the target query, covering workflow, fit, and next steps."},
];
for(const fixture of fixtures){const opportunity=clusterAndScoreOpportunities(fixture.metrics,[])[0];let after:string,why:string;try{const proposal=buildProposal(opportunity,fixture.snapshot);after=proposal.proposedMetaDescription??proposal.proposedContent??proposal.contentBrief??"No proposed value";why=`${proposal.observedProblem} ${proposal.rationale}`;}catch(error){if(!(error instanceof InsufficientSeoEvidenceError))throw error;after="No change recommended.";why=error.message;}console.log(JSON.stringify({fixture:true,path:fixture.path,before:fixture.before,after,why},null,2));}
